/** Grocery list UI copy — screens import from here. */
export const GROCERY_COPY = {
  listTitle: 'Grocery list',
  toBuySection: 'To buy',
  inCartSection: 'In cart',
  addItem: 'Add item',
  refresh: 'Refresh',
  clearCheckedItems: 'Clear checked items',
  clearCheckedTitle: 'Clear checked items',
  clearCheckedMessage: (count: number) => `Remove ${count} item(s) from your list?`,
  clear: 'Clear',
  cancel: 'Cancel',
  removeItem: 'Remove',
  removeItemTitle: 'Remove item',
  removeItemMessage: (name: string) => `Remove “${name}” from your list?`,
  undoRemoved: (name: string) => `Removed ${name}`,
  undoCleared: (count: number) => `Cleared ${count} item(s)`,
  allSetHint: 'All set — clear checked items or plan another meal.',
  nameRequiredTitle: 'Name required',
  nameRequiredMessage: 'Enter an item name.',
  quantityTitle: 'Quantity',
  quantityMessage: 'Enter a valid quantity.',
  addItemModalTitle: 'Add item',
  itemNamePlaceholder: 'Item name',
  qtyPlaceholder: 'Qty',
  unitPlaceholder: 'Unit',
  aisleLabel: 'Aisle',
  addToList: 'Add to list',
  shopThisList: (count: number) => `Shop this list (${count})`,
  plannedMealsLine: (count: number) => `${count} planned meal(s) · only buy what recipes still need`,
  toBuyInCartLine: (open: number, checked: number) => `${open} to buy · ${checked} in cart`,
} as const;
