/**
 * Pantry photo scan name cleanup — store brands and common product phrasing → recipe ingredients.
 * Applied in `ingredientNormalize.ts` before tokenization (does not replace INGREDIENT_SYNONYMS matching).
 */

/** Store / house brands stripped as whole-word prefixes (longest matched first at runtime). */
export const PANTRY_SCAN_STRIP_BRANDS = [
  'essential everyday',
  'signature select',
  'great value',
  'good gather',
  'kirkland',
  'kroger',
  'member mark',
  'trader joe',
  'trader joes',
  'simply done',
  'vanity fair',
  'good and gather',
  'winco',
  'campbell',
  'campbells',
  'del monte',
  'classico',
  'libby',
  'libbys',
  'dennison',
  'dennisons',
  'maria',
  'la costena',
  'la costeña',
  'victoria',
  'manwich',
  'hunt',
  'hunts',
  'progresso',
  'heinz',
  'kraft',
  'jif',
  'skippy',
  'quaker',
  'minute',
  'hungry jack',
  'country time',
  'hidden valley',
  'olive garden',
  'pillsbury',
  'general mills',
  'kellogg',
  'kelloggs',
  'post',
  'zesta',
  'ritz',
  'rold gold',
  'planters',
  'pearls',
  'snack factory',
  'town house',
  'good gather',
] as const;

/**
 * Phrase rewrites after brand strip (substring match, longest keys first).
 * Values are recipe-facing ingredient names (still run through normalize/tokenize).
 */
export const PANTRY_SCAN_PHRASE_SYNONYMS: Readonly<Record<string, string>> = {
  '100 pure pumpkin': 'pumpkin puree',
  'pure pumpkin': 'pumpkin puree',
  '100 pumpkin': 'pumpkin puree',
  oatmeal: 'oats',
  'old fashioned oats': 'oats',
  'old fashioned oats': 'oats',
  'pancake syrup': 'pancake syrup',
  'maple syrup': 'maple syrup',
  syrup: 'pancake syrup',
  'hawaiian rolls': 'rolls',
  'king hawaiian rolls': 'rolls',
  'king hawaiian sweet rolls': 'rolls',
  'hawaiian sweet rolls': 'rolls',
  'sloppy joe sauce': 'sloppy joe sauce',
  'sloppy joe': 'sloppy joe sauce',
  'cream of mushroom': 'cream of mushroom soup',
  'cream of chicken': 'cream of chicken soup',
  'macaroni cheese': 'macaroni and cheese',
  'mac and cheese': 'macaroni and cheese',
  'mac n cheese': 'macaroni and cheese',
  'all purpose flour': 'all-purpose flour',
  'cake mix': 'cake mix',
  'tomato soup condensed': 'tomato soup',
  'chicken rice mix': 'rice mix',
  'rice a roni': 'rice mix',
};
