/**
 * Recipe import — client config and copy.
 */

export const RECIPE_IMPORT = {
  enabled: true,
  /** Client fetch timeout; edge function budget is ~90s. */
  requestTimeoutMs: 95_000,
  proxyUrl: process.env.EXPO_PUBLIC_RECIPE_IMPORT_URL ?? '',
  maxPhotos: 4,
  /** Downscale before upload so edge requests stay small; text stays readable. */
  photoUploadMaxLongEdge: 1600,
  photoUploadJpegQuality: 0.8,
  maxVideoBytes: 104_857_600,
  videoMimeTypes: ['video/mp4', 'video/quicktime', 'video/webm'] as const,
  rateLimitMessage: 'Too many imports — wait a minute and try again.',
  notConfiguredMessage:
    'Recipe import is not available on this app yet. Ask an admin to finish setup.',
  invalidUrlMessage: 'Paste a link or recipe text to import.',
  notRecipeMessage: 'We could not find a recipe at that link. Try a different URL.',
  importFailedMessage: 'Could not import that recipe right now. Check your connection and try again.',
  importBusyMessage: 'Import is busy right now. Try again in a moment.',
  uploadBucket: 'recipe-import-uploads',
} as const;

export const RECIPE_IMPORT_COPY = {
  importButton: 'Import',
  importButtonAccessibility: 'Import recipe',
  importBoxPlaceholder: 'Paste a link or recipe text',
  importBoxLabel: 'Paste a video link or recipe text',
  redditPasteTip:
    "Reddit doesn't let apps read posts. Copy the recipe text or screenshot it, then paste it here or tap 📷.",
  removeSourceCta: 'Remove source',
  removeSourceAccessibility: 'Remove recipe source link and credit',
  cameraAccessibility: 'Snap or choose a recipe photo',
  importCta: 'Import',
  importing: 'Reading recipe…',
  needMoreHint: 'Couldn’t find the recipe — add a photo or video?',
  addPhotoCta: 'Add photo',
  addVideoCta: 'Add video',
  reviewTitle: 'Review before saving',
  reviewSubtitle: 'Edit anything that looks off, then save to your collection.',
  saveCta: 'Save recipe',
  saving: 'Saving…',
  cancel: 'Cancel',
  guestSignInMessage: 'Sign in to save imported recipes to your account.',
  guestSignInCta: 'Sign in',
  yourRecipeBadge: 'Your recipe',
  viewOriginal: 'Watch original video',
  viewOriginalPost: 'View original post',
  viewOriginalAccessibility: 'Watch original recipe video',
  viewOriginalPostAccessibility: 'View original Reddit post',
  byCreator: (name: string) => `By ${name}`,
  creatorLinkAccessibility: (name: string) => `Open ${name} profile or channel`,
  creditSeparator: ' · ',
  watchOnYouTube: 'Watch on YouTube',
  youtubeCredit: (channel: string) => `Recipe video by ${channel}`,
  youtubeCreditUnknown: 'Recipe video on YouTube',
  socialCredit: (handle: string) => `Recipe from ${handle}`,
  seeAuthorVersion: 'See the author’s version',
  manualCaptionHint:
    'Instagram and Facebook block automatic captions — paste the caption or add a screenshot.',
  socialCaptionLabel: 'Caption text',
  socialCaptionPlaceholder: 'Paste the recipe caption from the post…',
  importFromCaptionCta: 'Import from caption',
  sourceLinkLabel: 'Source link',
  stepsTitle: 'Instructions',
  noSteps: 'No steps were found — check the original link.',
  fallbackTitle: 'Try another way',
  youtubeFound: (channel: string) => `Found this on YouTube from ${channel}`,
  youtubeConfirmCta: 'Use this video',
  uploadVideoCta: 'Upload saved video',
  screenshotCta: 'Upload screenshot',
  pickPhotosCta: 'Choose photos',
  takePhotoCta: 'Take photo',
  addMissingGroceryCta: 'Add missing to grocery list',
  photoScanHint: '1–4 pages — printed or handwritten recipe cards.',
} as const;
