/**
 * Typical US retail package prices for common grocery ingredients.
 * Sources: U.S. Bureau of Labor Statistics Average Retail Food and Energy Prices
 * (https://www.bls.gov/regions/mid-atlantic/data/averageretailfoodandenergyprices_us_table.htm)
 * and USDA Agricultural Marketing Service retail summaries. Figures are approximate
 * national averages for common package sizes (not live store quotes).
 */
import type { BasePriceEntry } from './types';

function e(
  key: string,
  aliases: string[],
  packageAmount: number,
  packageUnit: string,
  packagePrice: number,
): BasePriceEntry {
  return { key, aliases, packageAmount, packageUnit, packagePrice };
}

export const BASE_PRICE_ENTRIES: BasePriceEntry[] = [
  e('chicken_breast', ['chicken breast', 'boneless chicken breast', 'skinless chicken breast'], 1, 'lb', 4.29),
  e('chicken_thigh', ['chicken thigh', 'chicken thighs', 'boneless chicken thigh'], 1, 'lb', 3.49),
  e('chicken_whole', ['whole chicken', 'chicken'], 1, 'lb', 2.19),
  e('chicken_drumstick', ['chicken drumstick', 'chicken drumsticks', 'drumsticks'], 1, 'lb', 2.49),
  e('ground_beef', ['ground beef', 'hamburger', 'minced beef'], 1, 'lb', 5.49),
  e('ground_turkey', ['ground turkey', 'turkey ground'], 1, 'lb', 4.99),
  e('beef_steak', ['steak', 'beef steak', 'sirloin', 'ribeye', 'flank steak'], 1, 'lb', 9.99),
  e('beef_roast', ['beef roast', 'pot roast', 'chuck roast'], 1, 'lb', 6.99),
  e('pork_chop', ['pork chop', 'pork chops'], 1, 'lb', 4.49),
  e('pork_loin', ['pork loin', 'pork tenderloin'], 1, 'lb', 4.99),
  e('bacon', ['bacon', 'bacon strips'], 16, 'oz', 6.49),
  e('sausage', ['sausage', 'breakfast sausage', 'italian sausage'], 12, 'oz', 4.49),
  e('ham', ['ham', 'deli ham', 'sliced ham'], 16, 'oz', 5.99),
  e('hot_dog', ['hot dog', 'hot dogs', 'frankfurter'], 12, 'oz', 3.99),
  e('salmon', ['salmon', 'salmon fillet'], 1, 'lb', 9.99),
  e('shrimp', ['shrimp', 'prawns'], 12, 'oz', 8.99),
  e('tilapia', ['tilapia', 'tilapia fillet'], 1, 'lb', 6.99),
  e('tuna_canned', ['canned tuna', 'tuna can', 'tuna in water'], 5, 'oz', 1.49),
  e('cod', ['cod', 'cod fillet'], 1, 'lb', 7.99),
  e('eggs', ['egg', 'eggs', 'large eggs'], 12, 'each', 3.29),
  e('milk', ['milk', 'whole milk', '2% milk', 'skim milk'], 1, 'gal', 3.79),
  e('butter', ['butter', 'unsalted butter', 'salted butter'], 16, 'oz', 4.99),
  e('cheddar', ['cheddar', 'cheddar cheese', 'shredded cheddar'], 8, 'oz', 3.49),
  e('mozzarella', ['mozzarella', 'mozzarella cheese', 'fresh mozzarella'], 8, 'oz', 3.99),
  e('parmesan', ['parmesan', 'parmesan cheese', 'grated parmesan'], 8, 'oz', 4.49),
  e('cream_cheese', ['cream cheese'], 8, 'oz', 2.49),
  e('sour_cream', ['sour cream'], 16, 'oz', 2.49),
  e('yogurt', ['yogurt', 'plain yogurt', 'greek yogurt'], 32, 'oz', 4.49),
  e('heavy_cream', ['heavy cream', 'whipping cream'], 16, 'fl oz', 4.29),
  e('half_and_half', ['half and half'], 32, 'fl oz', 3.49),
  e('cottage_cheese', ['cottage cheese'], 16, 'oz', 3.29),
  e('feta', ['feta', 'feta cheese'], 8, 'oz', 4.29),
  e('ricotta', ['ricotta', 'ricotta cheese'], 15, 'oz', 3.99),
  e('onion', ['onion', 'yellow onion', 'white onion', 'onions'], 3, 'lb', 2.49),
  e('red_onion', ['red onion'], 2, 'lb', 2.99),
  e('garlic', ['garlic', 'garlic clove', 'garlic cloves'], 3, 'each', 1.49),
  e('potato', ['potato', 'potatoes', 'russet potato'], 5, 'lb', 4.49),
  e('sweet_potato', ['sweet potato', 'sweet potatoes', 'yam'], 3, 'lb', 3.49),
  e('carrot', ['carrot', 'carrots'], 2, 'lb', 1.99),
  e('celery', ['celery', 'celery stalk'], 1, 'each', 1.99),
  e('broccoli', ['broccoli', 'broccoli florets'], 1, 'lb', 2.49),
  e('cauliflower', ['cauliflower'], 1, 'each', 3.49),
  e('spinach', ['spinach', 'baby spinach'], 10, 'oz', 3.49),
  e('kale', ['kale'], 1, 'bunch', 2.49),
  e('lettuce', ['lettuce', 'romaine', 'romaine lettuce', 'iceberg lettuce'], 1, 'each', 2.29),
  e('tomato', ['tomato', 'tomatoes', 'roma tomato'], 1, 'lb', 2.49),
  e('cherry_tomato', ['cherry tomato', 'cherry tomatoes', 'grape tomatoes'], 10, 'oz', 3.49),
  e('cucumber', ['cucumber'], 1, 'each', 0.99),
  e('bell_pepper', ['bell pepper', 'bell peppers', 'red pepper', 'green pepper'], 1, 'each', 1.29),
  e('jalapeno', ['jalapeno', 'jalapeño'], 4, 'oz', 1.49),
  e('mushroom', ['mushroom', 'mushrooms', 'button mushrooms'], 8, 'oz', 2.49),
  e('zucchini', ['zucchini'], 1, 'lb', 1.99),
  e('squash', ['squash', 'butternut squash'], 1, 'lb', 1.79),
  e('corn', ['corn', 'corn on the cob', 'sweet corn'], 4, 'each', 2.49),
  e('green_beans', ['green beans', 'green bean'], 12, 'oz', 2.49),
  e('peas_frozen', ['frozen peas', 'peas frozen'], 16, 'oz', 2.29),
  e('asparagus', ['asparagus'], 1, 'lb', 3.99),
  e('avocado', ['avocado', 'avocados'], 1, 'each', 1.49),
  e('lemon', ['lemon', 'lemons'], 1, 'each', 0.79),
  e('lime', ['lime', 'limes'], 1, 'each', 0.49),
  e('apple', ['apple', 'apples', 'gala apple'], 3, 'lb', 4.49),
  e('banana', ['banana', 'bananas'], 1, 'lb', 0.69),
  e('orange', ['orange', 'oranges'], 4, 'lb', 5.49),
  e('berries', ['strawberries', 'blueberries', 'raspberries'], 6, 'oz', 3.99),
  e('grapes', ['grapes'], 2, 'lb', 4.99),
  e('flour', ['flour', 'all purpose flour', 'all-purpose flour', 'ap flour'], 5, 'lb', 3.49),
  e('bread_flour', ['bread flour'], 5, 'lb', 4.49),
  e('sugar', ['sugar', 'granulated sugar', 'white sugar'], 4, 'lb', 3.99),
  e('brown_sugar', ['brown sugar', 'light brown sugar'], 32, 'oz', 3.29),
  e('powdered_sugar', ['powdered sugar', 'confectioners sugar'], 32, 'oz', 3.49),
  e('rice', ['rice', 'white rice', 'long grain rice'], 2, 'lb', 2.99),
  e('brown_rice', ['brown rice'], 2, 'lb', 3.49),
  e('jasmine_rice', ['jasmine rice'], 2, 'lb', 3.99),
  e('pasta', ['pasta', 'spaghetti', 'penne', 'linguine', 'fettuccine'], 16, 'oz', 1.49),
  e('egg_noodles', ['egg noodles', 'noodles'], 12, 'oz', 2.29),
  e('bread', ['bread', 'sandwich bread', 'loaf bread'], 20, 'oz', 2.99),
  e('tortilla', ['tortilla', 'tortillas', 'flour tortilla'], 10, 'each', 3.49),
  e('pita', ['pita', 'pita bread'], 6, 'each', 3.29),
  e('oats', ['oats', 'rolled oats', 'old fashioned oats'], 42, 'oz', 4.49),
  e('quinoa', ['quinoa'], 16, 'oz', 4.99),
  e('couscous', ['couscous'], 10, 'oz', 2.49),
  e('cornmeal', ['cornmeal', 'corn meal'], 24, 'oz', 2.99),
  e('breadcrumbs', ['breadcrumbs', 'bread crumbs', 'panko'], 15, 'oz', 2.49),
  e('baking_powder', ['baking powder'], 8, 'oz', 2.29),
  e('baking_soda', ['baking soda'], 16, 'oz', 1.49),
  e('yeast', ['yeast', 'active dry yeast'], 3, 'each', 1.99),
  e('cocoa', ['cocoa', 'cocoa powder', 'unsweetened cocoa'], 8, 'oz', 3.99),
  e('chocolate_chips', ['chocolate chips', 'semi sweet chocolate chips'], 12, 'oz', 3.49),
  e('vanilla_extract', ['vanilla', 'vanilla extract'], 2, 'fl oz', 4.99),
  e('olive_oil', ['olive oil', 'extra virgin olive oil'], 17, 'fl oz', 7.99),
  e('vegetable_oil', ['vegetable oil', 'canola oil', 'cooking oil'], 48, 'fl oz', 6.99),
  e('coconut_oil', ['coconut oil'], 14, 'oz', 6.49),
  e('sesame_oil', ['sesame oil'], 5, 'fl oz', 4.49),
  e('vinegar', ['vinegar', 'white vinegar', 'apple cider vinegar'], 32, 'fl oz', 2.49),
  e('balsamic', ['balsamic vinegar', 'balsamic'], 8.5, 'fl oz', 4.49),
  e('soy_sauce', ['soy sauce'], 15, 'fl oz', 2.99),
  e('worcestershire', ['worcestershire sauce'], 10, 'fl oz', 3.49),
  e('ketchup', ['ketchup', 'catsup'], 32, 'oz', 3.29),
  e('mustard', ['mustard', 'yellow mustard', 'dijon mustard'], 14, 'oz', 1.99),
  e('mayonnaise', ['mayonnaise', 'mayo'], 30, 'fl oz', 4.49),
  e('hot_sauce', ['hot sauce', 'sriracha'], 12, 'fl oz', 3.99),
  e('bbq_sauce', ['bbq sauce', 'barbecue sauce'], 18, 'oz', 2.99),
  e('tomato_sauce', ['tomato sauce', 'marinara', 'pasta sauce'], 24, 'oz', 2.49),
  e('tomato_paste', ['tomato paste'], 6, 'oz', 1.29),
  e('diced_tomatoes', ['diced tomatoes', 'canned tomatoes', 'crushed tomatoes'], 14.5, 'oz', 1.29),
  e('chicken_broth', ['chicken broth', 'chicken stock', 'broth'], 32, 'fl oz', 2.49),
  e('beef_broth', ['beef broth', 'beef stock'], 32, 'fl oz', 2.79),
  e('vegetable_broth', ['vegetable broth', 'vegetable stock'], 32, 'fl oz', 2.49),
  e('coconut_milk', ['coconut milk'], 13.5, 'fl oz', 2.29),
  e('beans_black', ['black beans', 'canned black beans'], 15, 'oz', 1.19),
  e('beans_kidney', ['kidney beans', 'red kidney beans'], 15, 'oz', 1.19),
  e('beans_pinto', ['pinto beans', 'canned pinto beans'], 15, 'oz', 1.19),
  e('chickpeas', ['chickpeas', 'garbanzo beans', 'canned chickpeas'], 15, 'oz', 1.29),
  e('lentils', ['lentils', 'dry lentils'], 16, 'oz', 2.49),
  e('peanut_butter', ['peanut butter'], 16, 'oz', 3.49),
  e('jam', ['jam', 'jelly', 'grape jelly'], 18, 'oz', 3.29),
  e('honey', ['honey'], 12, 'oz', 5.99),
  e('maple_syrup', ['maple syrup'], 12, 'fl oz', 7.99),
  e('nuts_almond', ['almonds', 'sliced almonds'], 8, 'oz', 4.99),
  e('nuts_walnut', ['walnuts', 'chopped walnuts'], 8, 'oz', 4.49),
  e('raisins', ['raisins'], 12, 'oz', 3.49),
  e('salt', ['table salt', 'kosher salt', 'sea salt'], 26, 'oz', 1.49),
  e('black_pepper', ['black pepper', 'ground black pepper', 'pepper'], 4, 'oz', 3.99),
  e('paprika', ['paprika'], 2.5, 'oz', 2.49),
  e('cumin', ['cumin', 'ground cumin'], 2, 'oz', 2.99),
  e('chili_powder', ['chili powder'], 2.5, 'oz', 2.49),
  e('cinnamon', ['cinnamon', 'ground cinnamon'], 2.37, 'oz', 3.49),
  e('oregano', ['oregano', 'dried oregano'], 0.75, 'oz', 2.29),
  e('basil_dried', ['dried basil'], 0.75, 'oz', 2.29),
  e('thyme', ['thyme', 'dried thyme'], 0.75, 'oz', 2.29),
  e('italian_seasoning', ['italian seasoning'], 0.95, 'oz', 2.49),
  e('garlic_powder', ['garlic powder'], 3.12, 'oz', 2.49),
  e('onion_powder', ['onion powder'], 2.62, 'oz', 2.49),
  e('ginger_ground', ['ground ginger', 'ginger powder'], 1.5, 'oz', 2.99),
  e('curry_powder', ['curry powder'], 2, 'oz', 3.49),
  e('turmeric', ['turmeric', 'ground turmeric'], 2, 'oz', 2.99),
  e('cayenne', ['cayenne', 'cayenne pepper'], 1.75, 'oz', 2.99),
  e('nutmeg', ['nutmeg', 'ground nutmeg'], 1.1, 'oz', 3.99),
  e('bay_leaf', ['bay leaf', 'bay leaves'], 0.12, 'oz', 2.49),
  e('parsley_fresh', ['parsley', 'fresh parsley'], 1, 'bunch', 1.49),
  e('cilantro', ['cilantro', 'fresh cilantro', 'coriander leaves'], 1, 'bunch', 1.49),
  e('basil_fresh', ['fresh basil', 'basil leaves'], 0.75, 'oz', 2.99),
  e('ginger_root', ['ginger', 'fresh ginger'], 4, 'oz', 1.99),
  e('green_onion', ['green onion', 'scallion', 'scallions'], 1, 'bunch', 1.29),
  e('cabbage', ['cabbage', 'green cabbage'], 1, 'each', 2.49),
  e('eggplant', ['eggplant'], 1, 'each', 2.29),
  e('tofu', ['tofu', 'firm tofu'], 14, 'oz', 2.49),
  e('tempeh', ['tempeh'], 8, 'oz', 3.99),
  e('frozen_broccoli', ['frozen broccoli'], 12, 'oz', 2.29),
  e('frozen_spinach', ['frozen spinach'], 10, 'oz', 1.99),
  e('frozen_berries', ['frozen berries', 'frozen strawberries'], 16, 'oz', 3.99),
  e('pizza_dough', ['pizza dough'], 16, 'oz', 3.49),
  e('pie_crust', ['pie crust', 'refrigerated pie crust'], 15, 'oz', 3.99),
  e('wonton_wrappers', ['wonton wrappers'], 14, 'oz', 3.49),
  e('rice_noodles', ['rice noodles'], 14, 'oz', 2.99),
  e('ramen', ['ramen', 'ramen noodles'], 3, 'oz', 0.49),
  e('polenta', ['polenta', 'corn grits'], 24, 'oz', 3.49),
  e('capers', ['capers'], 3, 'oz', 2.99),
  e('anchovies', ['anchovies', 'anchovy'], 2, 'oz', 3.49),
  e('olives', ['olives', 'black olives', 'green olives'], 6, 'oz', 2.49),
  e('pickles', ['pickles', 'dill pickles'], 24, 'fl oz', 3.49),
  e('salsa', ['salsa'], 16, 'oz', 3.29),
  e('taco_shells', ['taco shells', 'taco kit'], 12, 'each', 2.99),
  e('crackers', ['crackers', 'saltine crackers'], 16, 'oz', 3.49),
  e('chips', ['potato chips', 'tortilla chips'], 10, 'oz', 4.49),
  e('popcorn', ['popcorn kernels'], 32, 'oz', 3.99),
  e('coffee', ['coffee', 'ground coffee'], 12, 'oz', 7.99),
  e('tea', ['tea bags', 'black tea'], 20, 'each', 3.99),
  e('wine_cooking', ['cooking wine', 'white wine', 'red wine'], 25.4, 'fl oz', 4.99),
  e('beer', ['beer'], 12, 'fl oz', 1.29),
  e('lemon_juice', ['lemon juice', 'bottled lemon juice'], 15, 'fl oz', 2.49),
  e('lime_juice', ['lime juice'], 15, 'fl oz', 2.49),
  e('corn_starch', ['cornstarch', 'corn starch'], 16, 'oz', 2.49),
  e('gelatin', ['gelatin', 'unflavored gelatin'], 1, 'oz', 2.29),
  e('marshmallows', ['marshmallows'], 10, 'oz', 1.99),
  e('sprinkles', ['sprinkles', 'rainbow sprinkles'], 3.5, 'oz', 2.49),
  e('food_coloring', ['food coloring'], 1, 'each', 3.49),
  e('pumpkin_puree', ['pumpkin puree', 'canned pumpkin'], 15, 'oz', 2.49),
  e('applesauce', ['applesauce'], 23, 'oz', 2.49),
  e('cranberries', ['cranberries', 'dried cranberries'], 6, 'oz', 2.99),
  e('dates', ['dates', 'medjool dates'], 8, 'oz', 4.99),
  e('coconut_shredded', ['shredded coconut', 'coconut flakes'], 7, 'oz', 2.99),
  e('sesame_seeds', ['sesame seeds'], 3.5, 'oz', 2.99),
  e('flax_seed', ['flaxseed', 'flax seed'], 16, 'oz', 4.49),
  e('chia', ['chia seeds'], 12, 'oz', 5.99),
  e('protein_powder', ['protein powder'], 16, 'oz', 14.99),
  e('tortilla_chips', ['nacho chips'], 10, 'oz', 3.99),
  e('fish_sticks', ['fish sticks'], 18, 'oz', 5.99),
  e('chicken_nuggets', ['chicken nuggets'], 29, 'oz', 6.99),
  e('frozen_pizza', ['frozen pizza'], 20, 'oz', 5.99),
  e('ice_cream', ['ice cream'], 48, 'fl oz', 4.99),
  e('whipped_cream', ['whipped cream', 'cool whip'], 8, 'oz', 3.49),
  e('evaporated_milk', ['evaporated milk'], 12, 'fl oz', 1.79),
  e('condensed_milk', ['sweetened condensed milk', 'condensed milk'], 14, 'oz', 2.49),
  e('buttermilk', ['buttermilk'], 32, 'fl oz', 3.49),
  e('prosciutto', ['prosciutto'], 4, 'oz', 5.99),
  e('pepperoni', ['pepperoni'], 6, 'oz', 4.49),
  e('ground_pork', ['ground pork'], 1, 'lb', 4.29),
  e('lamb', ['lamb', 'ground lamb', 'lamb chop'], 1, 'lb', 9.99),
  e('duck', ['duck breast'], 1, 'lb', 8.99),
  e('crab', ['crab meat', 'crab'], 8, 'oz', 9.99),
  e('scallops', ['scallops', 'sea scallops'], 12, 'oz', 12.99),
  e('clams', ['clams', 'canned clams'], 6.5, 'oz', 2.49),
  e('mussels', ['mussels'], 1, 'lb', 5.99),
  e('squid', ['squid', 'calamari'], 1, 'lb', 7.99),
  e('artichoke', ['artichoke', 'artichoke hearts'], 14, 'oz', 2.99),
  e('beets', ['beets', 'canned beets'], 15, 'oz', 1.49),
  e('sun_dried_tomato', ['sun dried tomatoes', 'sun-dried tomatoes'], 7, 'oz', 3.99),
  e('roasted_red_pepper', ['roasted red peppers'], 12, 'oz', 2.99),
  e('enchilada_sauce', ['enchilada sauce'], 10, 'oz', 2.29),
  e('hoisin', ['hoisin sauce'], 9, 'oz', 3.49),
  e('fish_sauce', ['fish sauce'], 6.76, 'fl oz', 3.29),
  e('oyster_sauce', ['oyster sauce'], 9, 'oz', 3.49),
  e('rice_vinegar', ['rice vinegar'], 10, 'fl oz', 2.99),
  e('mirin', ['mirin'], 10, 'fl oz', 4.49),
  e('miso', ['miso paste', 'miso'], 13, 'oz', 4.99),
  e('tahini', ['tahini'], 16, 'oz', 6.99),
  e('harissa', ['harissa'], 10, 'oz', 4.99),
  e('gochujang', ['gochujang'], 17.6, 'oz', 5.99),
  e('kimchi', ['kimchi'], 14, 'oz', 4.99),
  e('sauerkraut', ['sauerkraut'], 14.5, 'oz', 2.49),
  e('hummus', ['hummus'], 10, 'oz', 3.99),
  e('guacamole', ['guacamole'], 8, 'oz', 4.49),
  e('queso', ['queso', 'nacho cheese'], 15, 'oz', 3.99),
  e('velveeta', ['velveeta', 'processed cheese'], 16, 'oz', 5.49),
  e('string_cheese', ['string cheese', 'mozzarella sticks'], 12, 'each', 3.99),
  e('bagel', ['bagel', 'bagels'], 6, 'each', 3.99),
  e('english_muffin', ['english muffin', 'english muffins'], 6, 'each', 3.49),
  e('croissant', ['croissant', 'croissants'], 4, 'each', 4.49),
  e('buns', ['hamburger buns', 'hot dog buns', 'buns'], 8, 'each', 2.99),
  e('rice_cake', ['rice cakes'], 4.13, 'oz', 2.99),
  e('granola', ['granola'], 12, 'oz', 4.49),
  e('cereal', ['cereal', 'breakfast cereal'], 14, 'oz', 4.99),
  e('instant_oatmeal', ['instant oatmeal', 'oatmeal packets'], 10, 'each', 3.49),
  e('pancake_mix', ['pancake mix'], 32, 'oz', 3.49),
  e('waffle_mix', ['waffle mix'], 28, 'oz', 3.49),
  e('bisquick', ['bisquick', 'baking mix'], 40, 'oz', 5.49),
  e('stuffing', ['stuffing mix'], 6, 'oz', 2.49),
  e('gravy_mix', ['gravy mix'], 0.87, 'oz', 1.49),
  e('bouillon', ['bouillon', 'bouillon cubes'], 3.5, 'oz', 2.49),
  e('tomato_soup', ['tomato soup', 'canned soup'], 10.75, 'oz', 1.49),
  e('chicken_noodle_soup', ['chicken noodle soup'], 10.5, 'oz', 1.79),
  e('refried_beans', ['refried beans'], 16, 'oz', 1.49),
  e('green_chiles', ['green chiles', 'diced green chiles'], 4, 'oz', 1.29),
  e('chipotle', ['chipotle in adobo', 'chipotle peppers'], 7, 'oz', 2.49),
  e('enchilada', ['enchilada'], 1, 'each', 2.99),
];

export const BASE_PRICE_BY_KEY = new Map(BASE_PRICE_ENTRIES.map((entry) => [entry.key, entry]));
