/**
 * Typical US retail grocery prices for cost-per-serving estimates.
 * Values are approximate averages informed by public BLS Average Price Data
 * (https://www.bls.gov/data/) and USDA Economic Research Service retail summaries
 * (https://www.ers.usda.gov/data-products/); not live market quotes.
 */
import type { BasePriceEntry } from './types';

export const BASE_PRICE_TABLE: BasePriceEntry[] = [
  // Produce
  { id: 'onion_yellow', name: 'yellow onion', aliases: ['onion', 'onions', 'sweet onion'], packageAmount: 3, packageUnit: 'lb', packagePrice: 2.49 },
  { id: 'garlic', name: 'garlic', aliases: ['garlic clove', 'fresh garlic'], packageAmount: 3, packageUnit: 'each', packagePrice: 1.29, gramsPerCup: 136 },
  { id: 'potato', name: 'potato', aliases: ['potatoes', 'russet potato', 'yukon gold'], packageAmount: 5, packageUnit: 'lb', packagePrice: 3.99 },
  { id: 'carrot', name: 'carrot', aliases: ['carrots'], packageAmount: 1, packageUnit: 'lb', packagePrice: 1.29 },
  { id: 'celery', name: 'celery', aliases: ['celery stalk'], packageAmount: 1, packageUnit: 'each', packagePrice: 1.99 },
  { id: 'broccoli', name: 'broccoli', aliases: ['broccoli florets'], packageAmount: 1, packageUnit: 'lb', packagePrice: 2.29 },
  { id: 'cauliflower', name: 'cauliflower', aliases: ['cauliflower florets'], packageAmount: 1, packageUnit: 'each', packagePrice: 3.49 },
  { id: 'spinach', name: 'spinach', aliases: ['baby spinach', 'fresh spinach'], packageAmount: 10, packageUnit: 'oz', packagePrice: 2.99, gramsPerCup: 30 },
  { id: 'lettuce_romaine', name: 'romaine lettuce', aliases: ['romaine', 'lettuce'], packageAmount: 1, packageUnit: 'each', packagePrice: 2.49 },
  { id: 'tomato', name: 'tomato', aliases: ['tomatoes', 'roma tomato', 'vine tomato'], packageAmount: 1, packageUnit: 'lb', packagePrice: 2.49 },
  { id: 'cucumber', name: 'cucumber', aliases: ['cucumbers'], packageAmount: 1, packageUnit: 'each', packagePrice: 0.89 },
  { id: 'bell_pepper', name: 'bell pepper', aliases: ['red bell pepper', 'green bell pepper', 'pepper'], packageAmount: 1, packageUnit: 'each', packagePrice: 1.29 },
  { id: 'jalapeno', name: 'jalapeno', aliases: ['jalapeno pepper', 'jalapeño'], packageAmount: 4, packageUnit: 'oz', packagePrice: 1.49 },
  { id: 'mushroom', name: 'mushroom', aliases: ['mushrooms', 'button mushrooms', 'cremini'], packageAmount: 8, packageUnit: 'oz', packagePrice: 2.49 },
  { id: 'zucchini', name: 'zucchini', aliases: ['summer squash'], packageAmount: 1, packageUnit: 'lb', packagePrice: 1.99 },
  { id: 'squash_butternut', name: 'butternut squash', aliases: ['butternut'], packageAmount: 1, packageUnit: 'lb', packagePrice: 1.49 },
  { id: 'sweet_potato', name: 'sweet potato', aliases: ['sweet potatoes', 'yam'], packageAmount: 1, packageUnit: 'lb', packagePrice: 1.29 },
  { id: 'corn', name: 'corn', aliases: ['corn on the cob', 'sweet corn'], packageAmount: 4, packageUnit: 'each', packagePrice: 2.99 },
  { id: 'green_beans', name: 'green beans', aliases: ['string beans', 'snap beans'], packageAmount: 12, packageUnit: 'oz', packagePrice: 2.49 },
  { id: 'asparagus', name: 'asparagus', aliases: [], packageAmount: 1, packageUnit: 'lb', packagePrice: 3.99 },
  { id: 'avocado', name: 'avocado', aliases: ['avocados'], packageAmount: 1, packageUnit: 'each', packagePrice: 1.25 },
  { id: 'lemon', name: 'lemon', aliases: ['lemons', 'lemon juice fresh'], packageAmount: 1, packageUnit: 'each', packagePrice: 0.79 },
  { id: 'lime', name: 'lime', aliases: ['limes', 'lime juice fresh'], packageAmount: 1, packageUnit: 'each', packagePrice: 0.49 },
  { id: 'apple', name: 'apple', aliases: ['apples', 'granny smith'], packageAmount: 3, packageUnit: 'lb', packagePrice: 4.49 },
  { id: 'banana', name: 'banana', aliases: ['bananas'], packageAmount: 1, packageUnit: 'lb', packagePrice: 0.69 },
  { id: 'berries_mixed', name: 'mixed berries', aliases: ['berries', 'strawberries', 'blueberries', 'raspberries'], packageAmount: 6, packageUnit: 'oz', packagePrice: 3.99 },
  { id: 'cilantro', name: 'cilantro', aliases: ['fresh cilantro', 'coriander leaves'], packageAmount: 1, packageUnit: 'bunch', packagePrice: 0.99 },
  { id: 'parsley', name: 'parsley', aliases: ['fresh parsley'], packageAmount: 1, packageUnit: 'bunch', packagePrice: 0.99 },
  { id: 'basil', name: 'basil', aliases: ['fresh basil'], packageAmount: 0.75, packageUnit: 'oz', packagePrice: 2.49 },
  { id: 'ginger', name: 'ginger', aliases: ['fresh ginger', 'ginger root'], packageAmount: 4, packageUnit: 'oz', packagePrice: 1.99 },
  { id: 'green_onion', name: 'green onion', aliases: ['scallion', 'scallions', 'spring onion'], packageAmount: 1, packageUnit: 'bunch', packagePrice: 0.99 },

  // Meat & poultry
  { id: 'chicken_breast', name: 'chicken breast', aliases: ['boneless skinless chicken breast', 'chicken breasts'], packageAmount: 24, packageUnit: 'oz', packagePrice: 6.99 },
  { id: 'chicken_thigh', name: 'chicken thigh', aliases: ['chicken thighs', 'boneless chicken thigh'], packageAmount: 24, packageUnit: 'oz', packagePrice: 5.49 },
  { id: 'chicken_whole', name: 'whole chicken', aliases: ['chicken'], packageAmount: 4, packageUnit: 'lb', packagePrice: 7.99 },
  { id: 'ground_beef', name: 'ground beef', aliases: ['ground chuck', 'hamburger meat', 'minced beef'], packageAmount: 1, packageUnit: 'lb', packagePrice: 5.99 },
  { id: 'beef_steak', name: 'beef steak', aliases: ['sirloin', 'ribeye', 'flank steak', 'skirt steak'], packageAmount: 1, packageUnit: 'lb', packagePrice: 9.99 },
  { id: 'pork_chop', name: 'pork chop', aliases: ['pork chops', 'boneless pork chop'], packageAmount: 1, packageUnit: 'lb', packagePrice: 4.49 },
  { id: 'pork_loin', name: 'pork tenderloin', aliases: ['pork loin', 'pork roast'], packageAmount: 1, packageUnit: 'lb', packagePrice: 5.49 },
  { id: 'bacon', name: 'bacon', aliases: ['thick cut bacon'], packageAmount: 12, packageUnit: 'oz', packagePrice: 5.99 },
  { id: 'sausage', name: 'sausage', aliases: ['italian sausage', 'breakfast sausage', 'pork sausage'], packageAmount: 1, packageUnit: 'lb', packagePrice: 4.99 },
  { id: 'ground_turkey', name: 'ground turkey', aliases: ['turkey ground'], packageAmount: 1, packageUnit: 'lb', packagePrice: 4.49 },
  { id: 'ground_pork', name: 'ground pork', aliases: [], packageAmount: 1, packageUnit: 'lb', packagePrice: 4.29 },
  { id: 'ham', name: 'ham', aliases: ['deli ham', 'cooked ham'], packageAmount: 8, packageUnit: 'oz', packagePrice: 3.99 },
  { id: 'salmon', name: 'salmon', aliases: ['salmon fillet', 'atlantic salmon'], packageAmount: 1, packageUnit: 'lb', packagePrice: 11.99 },
  { id: 'shrimp', name: 'shrimp', aliases: ['raw shrimp', 'peeled shrimp'], packageAmount: 12, packageUnit: 'oz', packagePrice: 8.99 },
  { id: 'tilapia', name: 'tilapia', aliases: ['tilapia fillet'], packageAmount: 1, packageUnit: 'lb', packagePrice: 6.99 },
  { id: 'tuna_canned', name: 'canned tuna', aliases: ['tuna', 'tuna in water'], packageAmount: 5, packageUnit: 'oz', packagePrice: 1.49 },
  { id: 'anchovy', name: 'anchovy', aliases: ['anchovies', 'anchovy paste'], packageAmount: 2, packageUnit: 'oz', packagePrice: 2.99 },

  // Dairy & eggs
  { id: 'milk', name: 'milk', aliases: ['whole milk', '2% milk', 'skim milk'], packageAmount: 1, packageUnit: 'gal', packagePrice: 3.79, gramsPerCup: 244 },
  { id: 'butter', name: 'butter', aliases: ['unsalted butter', 'salted butter'], packageAmount: 1, packageUnit: 'lb', packagePrice: 4.99, gramsPerCup: 227 },
  { id: 'eggs', name: 'eggs', aliases: ['egg', 'large eggs'], packageAmount: 1, packageUnit: 'dozen', packagePrice: 3.29 },
  { id: 'cheddar', name: 'cheddar cheese', aliases: ['cheddar', 'shredded cheddar'], packageAmount: 8, packageUnit: 'oz', packagePrice: 2.99, gramsPerCup: 113 },
  { id: 'mozzarella', name: 'mozzarella', aliases: ['mozzarella cheese', 'fresh mozzarella'], packageAmount: 8, packageUnit: 'oz', packagePrice: 3.49, gramsPerCup: 112 },
  { id: 'parmesan', name: 'parmesan', aliases: ['parmesan cheese', 'parmigiano'], packageAmount: 8, packageUnit: 'oz', packagePrice: 4.49, gramsPerCup: 100 },
  { id: 'cream_cheese', name: 'cream cheese', aliases: [], packageAmount: 8, packageUnit: 'oz', packagePrice: 2.49 },
  { id: 'sour_cream', name: 'sour cream', aliases: [], packageAmount: 16, packageUnit: 'oz', packagePrice: 2.29, gramsPerCup: 230 },
  { id: 'yogurt', name: 'yogurt', aliases: ['plain yogurt', 'greek yogurt'], packageAmount: 32, packageUnit: 'oz', packagePrice: 4.99, gramsPerCup: 245 },
  { id: 'heavy_cream', name: 'heavy cream', aliases: ['whipping cream', 'heavy whipping cream'], packageAmount: 1, packageUnit: 'pt', packagePrice: 3.49, gramsPerCup: 238 },
  { id: 'half_and_half', name: 'half and half', aliases: ['half & half'], packageAmount: 1, packageUnit: 'qt', packagePrice: 2.99 },
  { id: 'cottage_cheese', name: 'cottage cheese', aliases: [], packageAmount: 16, packageUnit: 'oz', packagePrice: 3.29 },
  { id: 'feta', name: 'feta cheese', aliases: ['feta'], packageAmount: 8, packageUnit: 'oz', packagePrice: 3.99 },

  // Dry goods & baking
  { id: 'flour', name: 'all purpose flour', aliases: ['flour', 'ap flour', 'bread flour'], packageAmount: 5, packageUnit: 'lb', packagePrice: 3.49, gramsPerCup: 120 },
  { id: 'sugar', name: 'granulated sugar', aliases: ['sugar', 'white sugar'], packageAmount: 4, packageUnit: 'lb', packagePrice: 3.99, gramsPerCup: 200 },
  { id: 'brown_sugar', name: 'brown sugar', aliases: ['light brown sugar', 'dark brown sugar'], packageAmount: 2, packageUnit: 'lb', packagePrice: 2.49, gramsPerCup: 220 },
  { id: 'powdered_sugar', name: 'powdered sugar', aliases: ['confectioners sugar'], packageAmount: 2, packageUnit: 'lb', packagePrice: 2.99, gramsPerCup: 120 },
  { id: 'rice_white', name: 'white rice', aliases: ['rice', 'long grain rice', 'jasmine rice', 'basmati rice'], packageAmount: 2, packageUnit: 'lb', packagePrice: 2.99, gramsPerCup: 185 },
  { id: 'rice_brown', name: 'brown rice', aliases: [], packageAmount: 2, packageUnit: 'lb', packagePrice: 3.49, gramsPerCup: 195 },
  { id: 'pasta', name: 'pasta', aliases: ['spaghetti', 'penne', 'macaroni', 'linguine', 'fettuccine'], packageAmount: 16, packageUnit: 'oz', packagePrice: 1.49 },
  { id: 'bread', name: 'bread', aliases: ['sandwich bread', 'white bread', 'wheat bread'], packageAmount: 1, packageUnit: 'each', packagePrice: 2.99 },
  { id: 'tortilla', name: 'tortilla', aliases: ['flour tortilla', 'corn tortilla', 'tortillas'], packageAmount: 10, packageUnit: 'each', packagePrice: 2.49 },
  { id: 'oats', name: 'oats', aliases: ['rolled oats', 'old fashioned oats'], packageAmount: 42, packageUnit: 'oz', packagePrice: 4.49, gramsPerCup: 80 },
  { id: 'quinoa', name: 'quinoa', aliases: [], packageAmount: 12, packageUnit: 'oz', packagePrice: 4.99, gramsPerCup: 170 },
  { id: 'couscous', name: 'couscous', aliases: [], packageAmount: 10, packageUnit: 'oz', packagePrice: 2.29, gramsPerCup: 173 },
  { id: 'cornmeal', name: 'cornmeal', aliases: ['polenta'], packageAmount: 24, packageUnit: 'oz', packagePrice: 2.99, gramsPerCup: 138 },
  { id: 'baking_powder', name: 'baking powder', aliases: [], packageAmount: 8, packageUnit: 'oz', packagePrice: 2.49, gramsPerCup: 192 },
  { id: 'baking_soda', name: 'baking soda', aliases: [], packageAmount: 16, packageUnit: 'oz', packagePrice: 1.29, gramsPerCup: 220 },
  { id: 'yeast', name: 'yeast', aliases: ['active dry yeast', 'instant yeast'], packageAmount: 3, packageUnit: 'each', packagePrice: 1.99 },
  { id: 'cornstarch', name: 'cornstarch', aliases: ['corn starch'], packageAmount: 16, packageUnit: 'oz', packagePrice: 2.49, gramsPerCup: 128 },
  { id: 'breadcrumbs', name: 'breadcrumbs', aliases: ['panko', 'bread crumbs'], packageAmount: 15, packageUnit: 'oz', packagePrice: 2.29, gramsPerCup: 108 },
  { id: 'crackers', name: 'crackers', aliases: ['saltine crackers'], packageAmount: 16, packageUnit: 'oz', packagePrice: 3.29 },

  // Oils & fats
  { id: 'olive_oil', name: 'olive oil', aliases: ['extra virgin olive oil', 'evoo'], packageAmount: 17, packageUnit: 'floz', packagePrice: 7.99, gramsPerCup: 216 },
  { id: 'vegetable_oil', name: 'vegetable oil', aliases: ['canola oil', 'cooking oil'], packageAmount: 48, packageUnit: 'floz', packagePrice: 4.99, gramsPerCup: 218 },
  { id: 'coconut_oil', name: 'coconut oil', aliases: [], packageAmount: 14, packageUnit: 'oz', packagePrice: 6.99, gramsPerCup: 218 },
  { id: 'sesame_oil', name: 'sesame oil', aliases: [], packageAmount: 5, packageUnit: 'floz', packagePrice: 3.99 },

  // Canned & jarred
  { id: 'tomato_paste', name: 'tomato paste', aliases: [], packageAmount: 6, packageUnit: 'oz', packagePrice: 0.99 },
  { id: 'tomato_sauce', name: 'tomato sauce', aliases: ['marinara sauce', 'pasta sauce'], packageAmount: 15, packageUnit: 'oz', packagePrice: 1.49 },
  { id: 'diced_tomatoes', name: 'diced tomatoes', aliases: ['canned tomatoes', 'crushed tomatoes', 'stewed tomatoes'], packageAmount: 14.5, packageUnit: 'oz', packagePrice: 1.29 },
  { id: 'chicken_broth', name: 'chicken broth', aliases: ['chicken stock', 'broth'], packageAmount: 32, packageUnit: 'floz', packagePrice: 2.49 },
  { id: 'beef_broth', name: 'beef broth', aliases: ['beef stock'], packageAmount: 32, packageUnit: 'floz', packagePrice: 2.79 },
  { id: 'vegetable_broth', name: 'vegetable broth', aliases: ['vegetable stock'], packageAmount: 32, packageUnit: 'floz', packagePrice: 2.49 },
  { id: 'beans_black', name: 'black beans', aliases: ['canned black beans'], packageAmount: 15, packageUnit: 'oz', packagePrice: 1.19 },
  { id: 'beans_kidney', name: 'kidney beans', aliases: ['red kidney beans', 'canned kidney beans'], packageAmount: 15, packageUnit: 'oz', packagePrice: 1.19 },
  { id: 'chickpeas', name: 'chickpeas', aliases: ['garbanzo beans', 'canned chickpeas'], packageAmount: 15, packageUnit: 'oz', packagePrice: 1.29 },
  { id: 'coconut_milk', name: 'coconut milk', aliases: ['canned coconut milk'], packageAmount: 13.5, packageUnit: 'floz', packagePrice: 2.49 },
  { id: 'peanut_butter', name: 'peanut butter', aliases: [], packageAmount: 16, packageUnit: 'oz', packagePrice: 3.49, gramsPerCup: 258 },
  { id: 'jam', name: 'jam', aliases: ['jelly', 'preserves'], packageAmount: 18, packageUnit: 'oz', packagePrice: 3.99 },
  { id: 'pickles', name: 'pickles', aliases: ['dill pickles', 'pickle relish'], packageAmount: 24, packageUnit: 'floz', packagePrice: 3.29 },
  { id: 'olives', name: 'olives', aliases: ['black olives', 'green olives'], packageAmount: 6, packageUnit: 'oz', packagePrice: 2.49 },
  { id: 'capers', name: 'capers', aliases: [], packageAmount: 3, packageUnit: 'oz', packagePrice: 2.99 },
  { id: 'salsa', name: 'salsa', aliases: ['jarred salsa'], packageAmount: 16, packageUnit: 'oz', packagePrice: 3.29 },

  // Condiments & sauces
  { id: 'ketchup', name: 'ketchup', aliases: [], packageAmount: 20, packageUnit: 'oz', packagePrice: 2.99 },
  { id: 'mustard', name: 'mustard', aliases: ['yellow mustard', 'dijon mustard'], packageAmount: 14, packageUnit: 'oz', packagePrice: 1.99 },
  { id: 'mayonnaise', name: 'mayonnaise', aliases: ['mayo'], packageAmount: 30, packageUnit: 'oz', packagePrice: 4.49 },
  { id: 'soy_sauce', name: 'soy sauce', aliases: ['tamari', 'low sodium soy sauce'], packageAmount: 10, packageUnit: 'floz', packagePrice: 2.99 },
  { id: 'worcestershire', name: 'worcestershire sauce', aliases: ['worcestershire'], packageAmount: 10, packageUnit: 'floz', packagePrice: 3.49 },
  { id: 'hot_sauce', name: 'hot sauce', aliases: ['sriracha', 'tabasco', 'chili sauce'], packageAmount: 5, packageUnit: 'floz', packagePrice: 3.29 },
  { id: 'vinegar', name: 'vinegar', aliases: ['white vinegar', 'apple cider vinegar', 'balsamic vinegar', 'rice vinegar'], packageAmount: 32, packageUnit: 'floz', packagePrice: 2.49 },
  { id: 'honey', name: 'honey', aliases: [], packageAmount: 12, packageUnit: 'oz', packagePrice: 5.99, gramsPerCup: 340 },
  { id: 'maple_syrup', name: 'maple syrup', aliases: ['pancake syrup'], packageAmount: 12, packageUnit: 'floz', packagePrice: 6.99 },
  { id: 'bbq_sauce', name: 'bbq sauce', aliases: ['barbecue sauce'], packageAmount: 18, packageUnit: 'oz', packagePrice: 2.99 },
  { id: 'teriyaki', name: 'teriyaki sauce', aliases: ['teriyaki'], packageAmount: 10, packageUnit: 'floz', packagePrice: 3.49 },
  { id: 'fish_sauce', name: 'fish sauce', aliases: [], packageAmount: 6.7, packageUnit: 'floz', packagePrice: 3.99 },
  { id: 'oyster_sauce', name: 'oyster sauce', aliases: [], packageAmount: 9, packageUnit: 'oz', packagePrice: 3.49 },

  // Spices & seasonings (priced when measured)
  { id: 'cumin', name: 'cumin', aliases: ['ground cumin', 'cumin powder'], packageAmount: 1.5, packageUnit: 'oz', packagePrice: 2.49, gramsPerCup: 100 },
  { id: 'paprika', name: 'paprika', aliases: ['smoked paprika'], packageAmount: 2.5, packageUnit: 'oz', packagePrice: 2.99 },
  { id: 'chili_powder', name: 'chili powder', aliases: ['chile powder'], packageAmount: 2.5, packageUnit: 'oz', packagePrice: 2.99 },
  { id: 'cinnamon', name: 'cinnamon', aliases: ['ground cinnamon'], packageAmount: 2.37, packageUnit: 'oz', packagePrice: 2.49 },
  { id: 'oregano', name: 'oregano', aliases: ['dried oregano'], packageAmount: 0.75, packageUnit: 'oz', packagePrice: 1.99 },
  { id: 'thyme', name: 'thyme', aliases: ['dried thyme'], packageAmount: 0.75, packageUnit: 'oz', packagePrice: 1.99 },
  { id: 'basil_dried', name: 'dried basil', aliases: ['basil dried'], packageAmount: 0.75, packageUnit: 'oz', packagePrice: 1.99 },
  { id: 'italian_seasoning', name: 'italian seasoning', aliases: ['italian herbs'], packageAmount: 0.75, packageUnit: 'oz', packagePrice: 2.29 },
  { id: 'garlic_powder', name: 'garlic powder', aliases: [], packageAmount: 3.12, packageUnit: 'oz', packagePrice: 2.49 },
  { id: 'onion_powder', name: 'onion powder', aliases: [], packageAmount: 2.62, packageUnit: 'oz', packagePrice: 2.49 },
  { id: 'curry_powder', name: 'curry powder', aliases: [], packageAmount: 2, packageUnit: 'oz', packagePrice: 3.49 },
  { id: 'turmeric', name: 'turmeric', aliases: ['ground turmeric'], packageAmount: 2, packageUnit: 'oz', packagePrice: 2.99 },
  { id: 'cayenne', name: 'cayenne pepper', aliases: ['cayenne'], packageAmount: 1.75, packageUnit: 'oz', packagePrice: 2.49 },
  { id: 'nutmeg', name: 'nutmeg', aliases: ['ground nutmeg'], packageAmount: 1.1, packageUnit: 'oz', packagePrice: 3.49 },
  { id: 'vanilla', name: 'vanilla extract', aliases: ['vanilla'], packageAmount: 2, packageUnit: 'floz', packagePrice: 4.99 },
  { id: 'bay_leaf', name: 'bay leaf', aliases: ['bay leaves'], packageAmount: 0.12, packageUnit: 'oz', packagePrice: 2.49 },

  // Nuts, seeds, chocolate
  { id: 'walnuts', name: 'walnuts', aliases: ['chopped walnuts'], packageAmount: 8, packageUnit: 'oz', packagePrice: 4.99, gramsPerCup: 120 },
  { id: 'almonds', name: 'almonds', aliases: ['sliced almonds'], packageAmount: 8, packageUnit: 'oz', packagePrice: 4.49, gramsPerCup: 143 },
  { id: 'peanuts', name: 'peanuts', aliases: ['roasted peanuts'], packageAmount: 16, packageUnit: 'oz', packagePrice: 3.99 },
  { id: 'pecans', name: 'pecans', aliases: [], packageAmount: 8, packageUnit: 'oz', packagePrice: 6.99 },
  { id: 'chocolate_chips', name: 'chocolate chips', aliases: ['semi sweet chocolate chips'], packageAmount: 12, packageUnit: 'oz', packagePrice: 3.99 },
  { id: 'cocoa', name: 'cocoa powder', aliases: ['unsweetened cocoa'], packageAmount: 8, packageUnit: 'oz', packagePrice: 3.49, gramsPerCup: 85 },

  // Frozen & misc
  { id: 'frozen_peas', name: 'frozen peas', aliases: ['peas'], packageAmount: 12, packageUnit: 'oz', packagePrice: 1.99 },
  { id: 'frozen_corn', name: 'frozen corn', aliases: [], packageAmount: 12, packageUnit: 'oz', packagePrice: 1.99 },
  { id: 'frozen_spinach', name: 'frozen spinach', aliases: [], packageAmount: 10, packageUnit: 'oz', packagePrice: 1.79 },
  { id: 'frozen_berries', name: 'frozen berries', aliases: ['frozen strawberries'], packageAmount: 12, packageUnit: 'oz', packagePrice: 3.49 },
  { id: 'pizza_dough', name: 'pizza dough', aliases: ['refrigerated pizza dough'], packageAmount: 1, packageUnit: 'lb', packagePrice: 3.99 },
  { id: 'pie_crust', name: 'pie crust', aliases: ['refrigerated pie crust'], packageAmount: 2, packageUnit: 'each', packagePrice: 3.99 },
  { id: 'tofu', name: 'tofu', aliases: ['firm tofu', 'extra firm tofu'], packageAmount: 14, packageUnit: 'oz', packagePrice: 2.49 },
  { id: 'tempeh', name: 'tempeh', aliases: [], packageAmount: 8, packageUnit: 'oz', packagePrice: 3.99 },
  { id: 'lentils', name: 'lentils', aliases: ['dry lentils', 'brown lentils'], packageAmount: 1, packageUnit: 'lb', packagePrice: 2.29, gramsPerCup: 192 },
  { id: 'split_peas', name: 'split peas', aliases: [], packageAmount: 1, packageUnit: 'lb', packagePrice: 2.19 },
  { id: 'chicken_wings', name: 'chicken wings', aliases: ['wings'], packageAmount: 2, packageUnit: 'lb', packagePrice: 6.99 },
  { id: 'ground_chicken', name: 'ground chicken', aliases: [], packageAmount: 1, packageUnit: 'lb', packagePrice: 4.99 },
  { id: 'lamb', name: 'lamb', aliases: ['ground lamb', 'lamb chop'], packageAmount: 1, packageUnit: 'lb', packagePrice: 9.99 },
  { id: 'prosciutto', name: 'prosciutto', aliases: [], packageAmount: 4, packageUnit: 'oz', packagePrice: 5.99 },
  { id: 'pepperoni', name: 'pepperoni', aliases: [], packageAmount: 6, packageUnit: 'oz', packagePrice: 3.99 },
  { id: 'cream_of_mushroom', name: 'cream of mushroom soup', aliases: ['cream of mushroom'], packageAmount: 10.5, packageUnit: 'oz', packagePrice: 1.49 },
  { id: 'evaporated_milk', name: 'evaporated milk', aliases: [], packageAmount: 12, packageUnit: 'floz', packagePrice: 1.79 },
  { id: 'sweetened_condensed', name: 'sweetened condensed milk', aliases: ['condensed milk'], packageAmount: 14, packageUnit: 'oz', packagePrice: 2.49 },
  { id: 'whipping_topping', name: 'whipped topping', aliases: ['cool whip'], packageAmount: 8, packageUnit: 'oz', packagePrice: 2.99 },
  { id: 'marshmallows', name: 'marshmallows', aliases: [], packageAmount: 10, packageUnit: 'oz', packagePrice: 1.99 },
  { id: 'graham_crackers', name: 'graham crackers', aliases: [], packageAmount: 14.4, packageUnit: 'oz', packagePrice: 3.99 },
  { id: 'pretzels', name: 'pretzels', aliases: [], packageAmount: 16, packageUnit: 'oz', packagePrice: 3.49 },
  { id: 'chips', name: 'potato chips', aliases: ['tortilla chips', 'corn chips'], packageAmount: 9.5, packageUnit: 'oz', packagePrice: 3.99 },
  { id: 'popcorn', name: 'popcorn kernels', aliases: ['popcorn'], packageAmount: 28, packageUnit: 'oz', packagePrice: 4.49 },
  { id: 'wine_cooking', name: 'cooking wine', aliases: ['white wine', 'red wine'], packageAmount: 25.4, packageUnit: 'floz', packagePrice: 4.99 },
  { id: 'beer', name: 'beer', aliases: ['lager', 'ale'], packageAmount: 12, packageUnit: 'floz', packagePrice: 1.29 },
  { id: 'mirin', name: 'mirin', aliases: [], packageAmount: 10, packageUnit: 'floz', packagePrice: 4.49 },
  { id: 'miso', name: 'miso paste', aliases: ['white miso', 'red miso'], packageAmount: 12, packageUnit: 'oz', packagePrice: 4.99 },
  { id: 'gochujang', name: 'gochujang', aliases: ['korean chili paste'], packageAmount: 17.6, packageUnit: 'oz', packagePrice: 5.99 },
  { id: 'hoisin', name: 'hoisin sauce', aliases: [], packageAmount: 9, packageUnit: 'oz', packagePrice: 3.49 },
  { id: 'tahini', name: 'tahini', aliases: ['sesame paste'], packageAmount: 16, packageUnit: 'oz', packagePrice: 6.99 },
  { id: 'coconut_flakes', name: 'coconut flakes', aliases: ['shredded coconut'], packageAmount: 7, packageUnit: 'oz', packagePrice: 2.99 },
  { id: 'raisins', name: 'raisins', aliases: ['golden raisins'], packageAmount: 12, packageUnit: 'oz', packagePrice: 3.49 },
  { id: 'dates', name: 'dates', aliases: ['medjool dates'], packageAmount: 8, packageUnit: 'oz', packagePrice: 4.99 },
  { id: 'sunflower_seeds', name: 'sunflower seeds', aliases: [], packageAmount: 16, packageUnit: 'oz', packagePrice: 3.99 },
  { id: 'pumpkin_seeds', name: 'pumpkin seeds', aliases: ['pepitas'], packageAmount: 8, packageUnit: 'oz', packagePrice: 4.49 },
  { id: 'sesame_seeds', name: 'sesame seeds', aliases: [], packageAmount: 3.5, packageUnit: 'oz', packagePrice: 2.99 },
  { id: 'flax_seed', name: 'flaxseed', aliases: ['ground flaxseed'], packageAmount: 16, packageUnit: 'oz', packagePrice: 4.99 },
  { id: 'chia', name: 'chia seeds', aliases: [], packageAmount: 12, packageUnit: 'oz', packagePrice: 6.99 },
  { id: 'protein_powder', name: 'protein powder', aliases: ['whey protein'], packageAmount: 2, packageUnit: 'lb', packagePrice: 24.99, gramsPerCup: 120 },
  { id: 'tortilla_chips', name: 'tortilla chips', aliases: [], packageAmount: 13, packageUnit: 'oz', packagePrice: 3.49 },
  { id: 'naan', name: 'naan', aliases: ['naan bread'], packageAmount: 4, packageUnit: 'each', packagePrice: 3.99 },
  { id: 'pita', name: 'pita bread', aliases: ['pita'], packageAmount: 6, packageUnit: 'each', packagePrice: 2.99 },
  { id: 'bagel', name: 'bagel', aliases: ['bagels'], packageAmount: 6, packageUnit: 'each', packagePrice: 3.99 },
  { id: 'english_muffin', name: 'english muffin', aliases: ['english muffins'], packageAmount: 6, packageUnit: 'each', packagePrice: 3.49 },
  { id: 'hamburger_buns', name: 'hamburger buns', aliases: ['buns', 'hot dog buns'], packageAmount: 8, packageUnit: 'each', packagePrice: 2.99 },
  { id: 'rice_noodles', name: 'rice noodles', aliases: ['rice vermicelli', 'pad thai noodles'], packageAmount: 14, packageUnit: 'oz', packagePrice: 2.49 },
  { id: 'egg_noodles', name: 'egg noodles', aliases: [], packageAmount: 12, packageUnit: 'oz', packagePrice: 2.29 },
  { id: 'lasagna_noodles', name: 'lasagna noodles', aliases: ['lasagna sheets'], packageAmount: 16, packageUnit: 'oz', packagePrice: 2.49 },
  { id: 'gnocchi', name: 'gnocchi', aliases: [], packageAmount: 16, packageUnit: 'oz', packagePrice: 3.99 },
  { id: 'ravioli', name: 'ravioli', aliases: ['cheese ravioli'], packageAmount: 20, packageUnit: 'oz', packagePrice: 5.99 },
  { id: 'frozen_fries', name: 'frozen french fries', aliases: ['french fries', 'frozen fries'], packageAmount: 32, packageUnit: 'oz', packagePrice: 4.49 },
  { id: 'hash_browns', name: 'hash browns', aliases: ['frozen hash browns'], packageAmount: 30, packageUnit: 'oz', packagePrice: 3.99 },
  { id: 'wonton_wrappers', name: 'wonton wrappers', aliases: ['gyoza wrappers'], packageAmount: 14, packageUnit: 'oz', packagePrice: 3.49 },
  { id: 'phyllo', name: 'phyllo dough', aliases: ['filo dough'], packageAmount: 16, packageUnit: 'oz', packagePrice: 4.99 },
  { id: 'puff_pastry', name: 'puff pastry', aliases: [], packageAmount: 17.3, packageUnit: 'oz', packagePrice: 4.99 },
  { id: 'crescent_rolls', name: 'crescent rolls', aliases: ['crescent roll dough'], packageAmount: 8, packageUnit: 'oz', packagePrice: 2.99 },
  { id: 'biscuit_dough', name: 'biscuit dough', aliases: ['refrigerated biscuits'], packageAmount: 16, packageUnit: 'oz', packagePrice: 3.49 },
  { id: 'sausage_links', name: 'sausage links', aliases: ['breakfast sausage links'], packageAmount: 12, packageUnit: 'oz', packagePrice: 3.99 },
  { id: 'hot_dogs', name: 'hot dogs', aliases: ['frankfurters'], packageAmount: 12, packageUnit: 'oz', packagePrice: 3.49 },
  { id: 'lunch_meat', name: 'deli turkey', aliases: ['turkey breast deli', 'ham deli', 'deli meat'], packageAmount: 9, packageUnit: 'oz', packagePrice: 4.99 },
  { id: 'rotisserie_chicken', name: 'rotisserie chicken', aliases: ['cooked chicken'], packageAmount: 1, packageUnit: 'each', packagePrice: 7.99 },
  { id: 'bratwurst', name: 'bratwurst', aliases: ['brats'], packageAmount: 14, packageUnit: 'oz', packagePrice: 4.99 },
  { id: 'kielbasa', name: 'kielbasa', aliases: ['polish sausage'], packageAmount: 14, packageUnit: 'oz', packagePrice: 4.49 },
  { id: 'chorizo', name: 'chorizo', aliases: ['mexican chorizo'], packageAmount: 12, packageUnit: 'oz', packagePrice: 3.99 },
  { id: 'italian_sausage_link', name: 'italian sausage link', aliases: [], packageAmount: 19, packageUnit: 'oz', packagePrice: 5.49 },
  { id: 'crab', name: 'crab meat', aliases: ['imitation crab', 'crab'], packageAmount: 8, packageUnit: 'oz', packagePrice: 4.99 },
  { id: 'clams', name: 'clams', aliases: ['canned clams'], packageAmount: 6.5, packageUnit: 'oz', packagePrice: 2.49 },
  { id: 'mussels', name: 'mussels', aliases: [], packageAmount: 1, packageUnit: 'lb', packagePrice: 5.99 },
  { id: 'scallops', name: 'scallops', aliases: ['sea scallops'], packageAmount: 12, packageUnit: 'oz', packagePrice: 12.99 },
  { id: 'cod', name: 'cod', aliases: ['cod fillet'], packageAmount: 1, packageUnit: 'lb', packagePrice: 8.99 },
  { id: 'catfish', name: 'catfish', aliases: ['catfish fillet'], packageAmount: 1, packageUnit: 'lb', packagePrice: 6.49 },
  { id: 'ground_veggie', name: 'veggie crumbles', aliases: ['meatless crumbles', 'plant based ground'], packageAmount: 12, packageUnit: 'oz', packagePrice: 4.99 },
  { id: 'veggie_burger', name: 'veggie burger', aliases: ['plant based burger patty'], packageAmount: 4, packageUnit: 'each', packagePrice: 5.99 },
  { id: 'nutritional_yeast', name: 'nutritional yeast', aliases: [], packageAmount: 5, packageUnit: 'oz', packagePrice: 5.99 },
  { id: 'applesauce', name: 'applesauce', aliases: [], packageAmount: 24, packageUnit: 'oz', packagePrice: 2.49 },
  { id: 'pumpkin_puree', name: 'pumpkin puree', aliases: ['canned pumpkin'], packageAmount: 15, packageUnit: 'oz', packagePrice: 2.29 },
  { id: 'pie_filling', name: 'pie filling', aliases: ['cherry pie filling', 'apple pie filling'], packageAmount: 21, packageUnit: 'oz', packagePrice: 3.99 },
  { id: 'frosting', name: 'frosting', aliases: ['cake frosting'], packageAmount: 16, packageUnit: 'oz', packagePrice: 2.99 },
  { id: 'cake_mix', name: 'cake mix', aliases: ['brownie mix'], packageAmount: 15.25, packageUnit: 'oz', packagePrice: 2.49 },
  { id: 'instant_pudding', name: 'instant pudding', aliases: ['pudding mix'], packageAmount: 3.4, packageUnit: 'oz', packagePrice: 1.29 },
  { id: 'gelatin', name: 'gelatin', aliases: ['jello', 'unflavored gelatin'], packageAmount: 3, packageUnit: 'oz', packagePrice: 2.49 },
  { id: 'food_coloring', name: 'food coloring', aliases: [], packageAmount: 1.2, packageUnit: 'floz', packagePrice: 3.99 },
  { id: 'sprinkles', name: 'sprinkles', aliases: ['rainbow sprinkles'], packageAmount: 3.5, packageUnit: 'oz', packagePrice: 2.99 },
  { id: 'lemonade', name: 'lemon juice bottled', aliases: ['bottled lemon juice'], packageAmount: 32, packageUnit: 'floz', packagePrice: 3.49 },
  { id: 'limeade', name: 'lime juice bottled', aliases: ['bottled lime juice'], packageAmount: 32, packageUnit: 'floz', packagePrice: 3.49 },
  { id: 'tomato_juice', name: 'tomato juice', aliases: ['v8'], packageAmount: 46, packageUnit: 'floz', packagePrice: 3.99 },
  { id: 'orange_juice', name: 'orange juice', aliases: ['oj'], packageAmount: 52, packageUnit: 'floz', packagePrice: 4.49 },
  { id: 'coffee', name: 'ground coffee', aliases: ['coffee'], packageAmount: 12, packageUnit: 'oz', packagePrice: 7.99 },
  { id: 'tea', name: 'tea bags', aliases: ['black tea', 'green tea'], packageAmount: 20, packageUnit: 'each', packagePrice: 3.99 },
];
