import type { StoreLocation } from '../deals/types';

/** Sample stores for link checks — three states, no hard-coded 209-only assumptions in resolver. */
export const STORE_LINK_SAMPLE_STORES: readonly StoreLocation[] = [
  {
    id: 'sample-save-mart-ca',
    name: 'Save Mart',
    chain: 'Save Mart',
    addressLine: '1441 E F St',
    city: 'Oakdale',
    state: 'CA',
    zip: '95361',
    lat: 37.766,
    lng: -120.847,
    source: 'osm',
    pricingSource: 'none',
    website: 'https://www.savemart.com/stores/693c06f6-0000-0000-0000-000000000000/OAKDALE/48/OAKDALE',
  },
  {
    id: 'sample-safeway-ca',
    name: 'Safeway',
    chain: 'Safeway',
    addressLine: '1187 S Main St',
    city: 'Manteca',
    state: 'CA',
    zip: '95337',
    lat: 37.797,
    lng: -121.216,
    source: 'osm',
    pricingSource: 'none',
    website: 'https://local.safeway.com/safeway/ca/manteca/1187-s-main-st.html',
  },
  {
    id: 'sample-publix-tx',
    name: 'Publix',
    chain: 'Publix',
    addressLine: '1234 W Anderson Ln',
    city: 'Austin',
    state: 'TX',
    zip: '78757',
    lat: 30.35,
    lng: -97.74,
    source: 'osm',
    pricingSource: 'none',
  },
  {
    id: 'sample-heb-tx',
    name: 'H-E-B',
    chain: 'H-E-B',
    addressLine: '5800 W Slaughter Ln',
    city: 'Austin',
    state: 'TX',
    zip: '78749',
    lat: 30.2,
    lng: -97.86,
    source: 'osm',
    pricingSource: 'none',
  },
  {
    id: 'sample-wegmans-ny',
    name: 'Wegmans',
    chain: 'Wegmans',
    addressLine: '3195 Monroe Ave',
    city: 'Rochester',
    state: 'NY',
    zip: '14618',
    lat: 43.12,
    lng: -77.55,
    source: 'osm',
    pricingSource: 'none',
  },
  {
    id: 'sample-hyvee-ia',
    name: 'Hy-Vee',
    chain: 'Hy-Vee',
    addressLine: '3330 Martin Luther King Jr Pkwy',
    city: 'Des Moines',
    state: 'IA',
    zip: '50310',
    lat: 41.6,
    lng: -93.6,
    source: 'osm',
    pricingSource: 'none',
  },
  {
    id: 'sample-grocery-outlet-ca',
    name: 'Grocery Outlet',
    chain: 'Grocery Outlet',
    addressLine: '1000 Oakdale Rd',
    city: 'Modesto',
    state: 'CA',
    zip: '95355',
    lat: 37.68,
    lng: -120.99,
    source: 'osm',
    pricingSource: 'none',
    website: 'https://www.groceryoutlet.com/circulars/storeid/192',
  },
  {
    id: 'sample-winco-no-zip',
    name: 'WinCo Foods',
    chain: 'WinCo Foods',
    addressLine: '200 Main St',
    city: 'Boise',
    state: 'ID',
    zip: '',
    lat: 43.61,
    lng: -116.2,
    source: 'osm',
    pricingSource: 'none',
  },
] as const;

export const STORE_LINK_FALLBACK_ZIP = '78701';
