import {
  FUZZY_MATCH_THRESHOLD,
  INGREDIENT_CATEGORY_GROUPS,
  INGREDIENT_STRIP_TOKENS,
  INGREDIENT_SYNONYMS,
  PANTRY_STAPLES,
} from '../../config/recipeMatchingConfig';

export {
  FUZZY_MATCH_THRESHOLD,
  INGREDIENT_CATEGORY_GROUPS,
  INGREDIENT_SYNONYMS,
  PANTRY_STAPLES,
};

export const STRIP_TOKENS = new Set<string>(INGREDIENT_STRIP_TOKENS);
