import type { LibraryRecipeRow } from './types';

export const DEMO_LIBRARY_RECIPE_ROWS: LibraryRecipeRow[] = [
  {
    id: 'demo-1',
    slug: 'sheet-pan-chicken-and-vegetables',
    title: 'Sheet Pan Chicken and Vegetables',
    dish_name: 'Sheet Pan Chicken and Vegetables',
    servings: 4,
    prep_minutes: 15,
    cook_minutes: 35,
    ingredients: [
      { name: 'boneless chicken thighs', quantity: 1.5, unit: 'lb' },
      { name: 'baby potatoes', quantity: 1, unit: 'lb' },
      { name: 'broccoli florets', quantity: 3, unit: 'cups' },
      { name: 'olive oil', quantity: 3, unit: 'tbsp' },
      { name: 'garlic powder', quantity: 1, unit: 'tsp' },
      { name: 'paprika', quantity: 1, unit: 'tsp' },
      { name: 'salt', quantity: 1, unit: 'tsp' },
      { name: 'black pepper', quantity: 0.5, unit: 'tsp' },
    ],
    steps: [
      'Heat the oven to 425°F. Line a large sheet pan with foil.',
      'Toss potatoes with half the oil and half the seasonings; spread on the pan and roast 10 minutes.',
      'Toss chicken and broccoli with remaining oil and seasonings; add to the pan.',
      'Roast until chicken reaches 165°F in the thickest part, about 20–25 minutes more.',
      'Rest 5 minutes before serving.',
    ],
    tags: ['sheet pan', 'quick', 'dinner'],
    cuisine: 'American',
    image_url: null,
    status: 'published',
    review_notes: null,
    model: 'demo',
    created_at: new Date(0).toISOString(),
  },
  {
    id: 'demo-2',
    slug: 'beef-and-bean-chili',
    title: 'Weeknight Beef and Bean Chili',
    dish_name: 'Beef and Bean Chili',
    servings: 4,
    prep_minutes: 15,
    cook_minutes: 40,
    ingredients: [
      { name: 'ground beef', quantity: 1, unit: 'lb' },
      { name: 'yellow onion', quantity: 1, unit: 'each' },
      { name: 'canned kidney beans', quantity: 2, unit: 'cans' },
      { name: 'canned diced tomatoes', quantity: 1, unit: 'can' },
      { name: 'tomato paste', quantity: 2, unit: 'tbsp' },
      { name: 'chili powder', quantity: 2, unit: 'tbsp' },
      { name: 'cumin', quantity: 1, unit: 'tsp' },
      { name: 'salt', quantity: 1, unit: 'tsp' },
    ],
    steps: [
      'Dice the onion. Drain and rinse the beans.',
      'Brown ground beef in a large pot over medium-high heat; drain excess fat.',
      'Add onion and cook until softened, about 5 minutes.',
      'Stir in tomato paste and spices; cook 1 minute.',
      'Add tomatoes, beans, and 1 cup water. Simmer 25–30 minutes until thickened.',
      'Season to taste and serve.',
    ],
    tags: ['budget', 'crockpot-friendly', 'dinner'],
    cuisine: 'American',
    image_url: null,
    status: 'published',
    review_notes: null,
    model: 'demo',
    created_at: new Date(0).toISOString(),
  },
];
