-- Seed trusted food creators (48 channels). Stats refreshed from YouTube API via creator-videos.

insert into public.recipe_creators (
  youtube_channel_id,
  display_name,
  handle,
  channel_url,
  subscriber_count,
  total_views,
  avg_views,
  avg_likes,
  rank,
  fit,
  source,
  enabled,
  notes
) values
  (
    'UCMyOj6fhvKFMjxUCp3b_3gA',
    'Nick DiGiovanni',
    '@NickDiGiovanni',
    'https://www.youtube.com/@NickDiGiovanni',
    47000000,
    24011492262,
    53041052,
    366125,
    1,
    'Low',
    'top25',
    true,
    'spectacle content, no recipe data to match pantries'
  ),
  (
    'UC0NkSnlCOhoODbykzZwpiDw',
    'albert_cancook',
    '@albert_cancook',
    'https://www.youtube.com/@albert_cancook',
    29300000,
    28520537740,
    1236992,
    31958,
    2,
    'Low',
    'top25',
    true,
    'novelty dishes, no written recipes'
  ),
  (
    'UCJFp8uSYCjXOMnkUyb3CQ3Q',
    'Tasty (BuzzFeed)',
    '@buzzfeedtasty',
    'https://www.youtube.com/@buzzfeedtasty',
    21200000,
    6656102484,
    65199,
    294,
    3,
    'High',
    'top25',
    true,
    'huge library of structured quick and budget recipes on tasty.co'
  ),
  (
    'UCjwmbv6NE4mOh8Z8VhPUx1Q',
    'Rosanna Pansino',
    '@RosannaPansino',
    'https://www.youtube.com/@RosannaPansino',
    14800000,
    5144686584,
    361584,
    11296,
    4,
    'Low',
    'top25',
    true,
    'dessert and novelty focus, inactive lately'
  ),
  (
    'UChBEbMKI1eCcejTtmI32UEw',
    'Joshua Weissman',
    '@JoshuaWeissman',
    'https://www.youtube.com/@JoshuaWeissman',
    10700000,
    2579324051,
    3550525,
    54727,
    5,
    'Low',
    'top25',
    true,
    'recent content is entertainment and reviews'
  ),
  (
    'UCJHA_jMfCvEnv-3kRjTCQXw',
    'Binging with Babish',
    '@bingingwithbabish',
    'https://www.youtube.com/@bingingwithbabish',
    10500000,
    2944049061,
    759485,
    16688,
    6,
    'Medium',
    'top25',
    true,
    'recipes are available but themed and entertainment-led, not weeknight-focused'
  ),
  (
    'UC_pT_Iz6XjuM-eMTlXghdfw',
    'Max the Meat Guy',
    '@maxthemeatguy',
    'https://www.youtube.com/@maxthemeatguy',
    10200000,
    7440731824,
    5983207,
    72888,
    7,
    'Low',
    'top25',
    true,
    'entertainment and reviews'
  ),
  (
    'UCbpMy0Fg74eXXkvxJrtEn3w',
    'Bon Appétit',
    '@bonappetit',
    'https://www.youtube.com/@bonappetit',
    7410000,
    2228937239,
    387623,
    3725,
    8,
    'Low',
    'top25',
    true,
    'restaurant and pro-chef content, not home recipes'
  ),
  (
    'UC8gFadPgK2r1ndqLI04Xvvw',
    'Maangchi',
    '@Maangchi',
    'https://www.youtube.com/@Maangchi',
    6530000,
    788857405,
    133862,
    5584,
    9,
    'Medium',
    'top25',
    true,
    'real recipes, some pantry-friendly (canned tuna), but niche ingredients and slow cadence'
  ),
  (
    'UCcjhYlL1WRBjKaJsMH_h7Lg',
    'Epicurious',
    '@epicurious',
    'https://www.youtube.com/@epicurious',
    6320000,
    1841320895,
    173229,
    1967,
    10,
    'Low/Medium',
    'top25',
    true,
    'little recipe content right now'
  ),
  (
    'UCTvYEid8tmg0jqGPDkehc_Q',
    'Preppy Kitchen',
    '@PreppyKitchen',
    'https://www.youtube.com/@PreppyKitchen',
    6230000,
    962111839,
    178137,
    3865,
    11,
    'Medium',
    'top25',
    true,
    'high-quality recipes but mostly baking, not dinners'
  ),
  (
    'UCfE5Cz44GlZVyoaYTHJbuZw',
    'Guga Foods',
    '@GugaFoods',
    'https://www.youtube.com/@GugaFoods',
    5860000,
    1344534146,
    908373,
    14343,
    12,
    'Low',
    'top25',
    true,
    'experiments and reviews'
  ),
  (
    'UCzH5n3Ih5kgQoiDAQt2FwLw',
    'LifebyMikeG (formerly Pro Home Cooks)',
    '@LifebyMikeG',
    'https://www.youtube.com/@LifebyMikeG',
    5380000,
    932108362,
    464513,
    10677,
    13,
    'Medium',
    'top25',
    true,
    'practical and anti-waste, but not recipe-card format'
  ),
  (
    'UCRIZtPl9nb9RiXc9btSTQNw',
    'Food Wishes (Chef John)',
    '@foodwishes',
    'https://www.youtube.com/@foodwishes',
    4700000,
    1159970085,
    181504,
    5921,
    14,
    'High',
    'top25',
    true,
    'dinner and budget recipes with structured written recipes'
  ),
  (
    'UCXGR70CkW_pXb8n52LzCCRw',
    'Mythical Kitchen',
    '@mythicalkitchen',
    'https://www.youtube.com/@mythicalkitchen',
    4590000,
    1810935209,
    1247638,
    23863,
    15,
    'Low',
    'top25',
    true,
    'celebrity and entertainment format'
  ),
  (
    'UCh8gHdtzO2tXd593_bjErWg',
    'Doobydobap',
    '@doobydobap',
    'https://www.youtube.com/@doobydobap',
    4500000,
    1765070589,
    575642,
    10681,
    16,
    'Low',
    'top25',
    true,
    'travel and vlog-led'
  ),
  (
    'UC-pC1xsFPzcrL09DaW4jlBA',
    'Natasha''s Kitchen',
    '@Natashaskitchen',
    'https://www.youtube.com/@Natashaskitchen',
    4130000,
    588692036,
    77703,
    3281,
    17,
    'High',
    'top25',
    true,
    'classic family dinners with complete ingredient lists'
  ),
  (
    'UCNbngWUqL2eqRw12yAwcICg',
    'Laura in the Kitchen',
    '@LauraintheKitchen',
    'https://www.youtube.com/@LauraintheKitchen',
    3970000,
    700049812,
    50653,
    1348,
    18,
    'High',
    'top25',
    true,
    'weeknight dinners with ingredients in the description'
  ),
  (
    'UCbRj3Tcy1Zoz3rcf83nW5kw',
    'SAM THE COOKING GUY',
    '@SAMTHECOOKINGGUY',
    'https://www.youtube.com/@SAMTHECOOKINGGUY',
    3870000,
    731592097,
    164521,
    4001,
    19,
    'High',
    'top25',
    true,
    'dinner-focused, frequent, written recipes'
  ),
  (
    'UC6tJ9C5SBvK6b-0cejoc4vg',
    'Smokin'' & Grillin wit AB',
    '@SmokinandGrillinwithAB',
    'https://www.youtube.com/@SmokinandGrillinwithAB',
    3810000,
    442519079,
    103102,
    2417,
    20,
    'High',
    'top25',
    true,
    'affordable comfort-food dinners, near-daily, written recipes'
  ),
  (
    'UClrMJRlvoyoWsVlB-7c61PQ',
    'Cowboy Kent Rollins',
    '@CowboyKentRollins',
    'https://www.youtube.com/@CowboyKentRollins',
    3570000,
    449685076,
    160840,
    4171,
    21,
    'Medium',
    'top25',
    true,
    'hearty budget dinners, but mixed with non-recipe videos'
  ),
  (
    'UCsEmkNdR_HQ_INJd_M9lULQ',
    'The Golden Balance',
    '@thegoldenbalance',
    'https://www.youtube.com/@thegoldenbalance',
    3570000,
    1646675451,
    330035,
    6887,
    22,
    'Medium',
    'top25',
    true,
    'meal-prep and weight-loss Shorts fit; long-form is travel'
  ),
  (
    'UC4tAgeVdaNB5vD_mBoxg50w',
    'Allrecipes',
    '@allrecipes',
    'https://www.youtube.com/@allrecipes',
    3550000,
    877559526,
    996801,
    19800,
    23,
    'High',
    'top25',
    true,
    'dinner and quick-meal recipes backed by a structured recipe database'
  ),
  (
    'UC8Y-jrV8oR3s2Ix4viDkZtA',
    'Food Network',
    '@foodnetwork',
    'https://www.youtube.com/@foodnetwork',
    3330000,
    1244483645,
    15413,
    223,
    24,
    'Medium',
    'top25',
    true,
    'good recipes buried among competition and reality clips'
  ),
  (
    'UCzqbfYjQmf9nLQPMxVgPhiA',
    'emmymade',
    '@emmymade',
    'https://www.youtube.com/@emmymade',
    3160000,
    661792812,
    120870,
    3259,
    25,
    'Medium/Low',
    'top25',
    true,
    'some cheap 10-minute meals, mostly curiosity content'
  ),
  (
    'UCxAS_aK7sS2x_bqnlJHDSHw',
    'America''s Test Kitchen',
    '@americastestkitchen',
    'https://www.youtube.com/@americastestkitchen',
    3040000,
    725367928,
    105407,
    2168,
    null,
    'High',
    'below_cutoff',
    true,
    'High (paywalled recipes are a caveat)'
  ),
  (
    'UCYidQwKhM3WTDKpT8pwfJzw',
    'Downshiftology',
    '@Downshiftology',
    'https://www.youtube.com/@Downshiftology',
    2730000,
    273318898,
    33104,
    1358,
    null,
    'High',
    'below_cutoff',
    true,
    'High (dinners), but low cadence'
  ),
  (
    'UCLGNeElk4sNgzUrZr0c9krA',
    'Chef Jean-Pierre',
    '@ChefJeanPierre',
    'https://www.youtube.com/@ChefJeanPierre',
    2480000,
    278702565,
    153768,
    10439,
    null,
    'Medium/High',
    'below_cutoff',
    true,
    'Medium/High'
  ),
  (
    'UCehYu6vFoOvu1MVPW24pUbQ',
    'Simply Mamá Cooks',
    '@SimplyMamaCooks',
    'https://www.youtube.com/@SimplyMamaCooks',
    1920000,
    313357793,
    46318,
    1877,
    null,
    'High',
    'below_cutoff',
    true,
    'High (pantry and budget focus, e.g. ''Canned Foods I Always Keep In My Pantry'')'
  ),
  (
    'UCqqJQ_cXSat0KIAVfIfKkVA',
    'J. Kenji López-Alt',
    '@JKenjiLopezAlt',
    'https://www.youtube.com/@JKenjiLopezAlt',
    1760000,
    298733894,
    95655,
    1362,
    null,
    'Medium/High',
    'below_cutoff',
    true,
    'Medium/High'
  ),
  (
    'UCn5fhcGRrCvrmFibPbT6q1A',
    'Brian Lagerstrom',
    '@BrianLagerstrom',
    'https://www.youtube.com/@BrianLagerstrom',
    1800000,
    235779978,
    189980,
    5824,
    null,
    'Medium/High',
    'below_cutoff',
    true,
    'Medium/High'
  ),
  (
    'UCi_58-g6BjEkhbYRtXBDTHg',
    'Julia Pacheco',
    '@JuliaPacheco',
    'https://www.youtube.com/@JuliaPacheco',
    1090000,
    156201377,
    114636,
    5205,
    null,
    'High',
    'below_cutoff',
    true,
    'High (budget dinner focus)'
  ),
  (
    'UCpqH8-BBNTsluhcOzFKWLuw',
    'MATTY MATHESON',
    '@mattymatheson',
    'https://www.youtube.com/@mattymatheson',
    1640000,
    248039951,
    168988,
    2791,
    null,
    'Medium',
    'david_pick',
    true,
    'approachable dinners and big reach, but no written recipes and he''s Canada-based'
  ),
  (
    'UCBlkFc1BBuLuTDYOzraIxnQ',
    'Jorts Kitchen',
    '@JortsKitchen',
    'https://www.youtube.com/@JortsKitchen',
    1080000,
    895609713,
    0,
    0,
    null,
    'Low/Medium',
    'david_pick',
    true,
    'creative and viral rather than pantry or weeknight focused; recipes are off-platform'
  ),
  (
    'UC0gy_bMDKfXyBgb6G2FFwHQ',
    'Landon Bridges',
    '@imlandn',
    'https://www.youtube.com/@imlandn',
    438000,
    261855756,
    110532,
    3826,
    null,
    'Low/Medium',
    'david_pick',
    true,
    'fun and viral but indulgent, and recipes are paywalled'
  ),
  (
    'UCEMj2h7pP4QWkoGnSmaiiYw',
    'The Plant Slant',
    '@theplantslant2431',
    'https://www.youtube.com/@theplantslant2431',
    2810000,
    5079756495,
    180566,
    5943,
    null,
    'Medium',
    'david_pick',
    true,
    'budget and healthy pantry-staple angle with huge Shorts reach, but no recipe data'
  ),
  (
    'UC-4es1WvtPLadTw-7zZrvjA',
    'Zach Rodriguez (zachwiththefatback)',
    '@zachwiththefatback',
    'https://www.youtube.com/@zachwiththefatback',
    650000,
    272553113,
    0,
    0,
    null,
    'Medium',
    'david_pick',
    true,
    'dinner-focused with written recipes off-platform, but more project cooking than quick or budget'
  ),
  (
    'UCCraUx678pr5_5A3PnV36lQ',
    'Justine''s Kitchen',
    '@justineskitchen',
    'https://www.youtube.com/@justineskitchen',
    1000000,
    678567578,
    65489,
    783,
    null,
    'High',
    'david_pick',
    true,
    'daily easy and crockpot weeknight dinners for busy home cooks (caveat: no written ingredient lists)'
  ),
  (
    'UCim1nv8VG_ituPkCll4v4eQ',
    'everydayisfeastday',
    '@everydayisfeastday',
    'https://www.youtube.com/@everydayisfeastday',
    340000,
    118034571,
    7507,
    283,
    null,
    'High',
    'david_pick',
    true,
    'weeknight and budget dinners with ingredient lists ready to parse'
  ),
  (
    'UCx2cbCojhLK2QFIhwjNQYgA',
    'Old''s Cool Kevmo (Chef Kevin Ashton)',
    '@oldscoolkevmo',
    'https://www.youtube.com/@oldscoolkevmo',
    1660000,
    724570673,
    0,
    0,
    null,
    'High',
    'david_pick',
    true,
    'comfort-food and weeknight dinners; full recipes on kevmoskitchen.com (paid subscription — never imported)'
  ),
  (
    'UCgpnjdjVpDEFtp1EtmPyLzQ',
    'RecipeTin Eats (Nagi Maehashi)',
    '@RecipeTinEats',
    'https://www.youtube.com/@RecipeTinEats',
    835000,
    275724536,
    36585,
    531,
    null,
    'High',
    'intl_added',
    true,
    'weeknight dinners with complete written recipes, posted almost daily'
  ),
  (
    'UCqRdvREgI2qLnKtiMfswzZQ',
    'Chef Jack Ovens',
    '@ChefJackOvens',
    'https://www.youtube.com/@ChefJackOvens',
    1660000,
    179681355,
    70546,
    1240,
    null,
    'High',
    'intl_added',
    true,
    'meal prep, budget and dinner focus with exact quantities'
  ),
  (
    'UC0alwLbzL_MzSRfV-eQTALw',
    'Kitchen Sanctuary',
    '@Kitchensanctuary',
    'https://www.youtube.com/@Kitchensanctuary',
    520000,
    91156995,
    22572,
    707,
    null,
    'High',
    'intl_added',
    true,
    'quick dinner recipes with written ingredients (smaller reach)'
  ),
  (
    'UCy_iF2lqOucgmK1BLCl-6vQ',
    'Recipe30 (Joel Mielle)',
    '@recipe30',
    'https://www.youtube.com/@recipe30',
    1650000,
    228643490,
    66094,
    1997,
    null,
    'Medium/High',
    'intl_added',
    true,
    'dinner focus with written recipes, but ingredients aren''t in the description'
  ),
  (
    'UC19OYOBqkgVqgTIQxbsPdlw',
    'ThatDudeCanCook (Sonny Hurrell)',
    '@thatdudecancook',
    'https://www.youtube.com/@thatdudecancook',
    2520000,
    844502928,
    234266,
    6706,
    null,
    'Medium/High',
    'intl_added',
    true,
    'strong engagement and dinner recipes, but written ingredients are inconsistent'
  ),
  (
    'UCsU15yvILBmnHPeAf4SFVaQ',
    'Glen And Friends Cooking',
    '@GlenAndFriendsCooking',
    'https://www.youtube.com/@GlenAndFriendsCooking',
    671000,
    125596480,
    32509,
    2430,
    null,
    'Medium/High',
    'intl_added',
    true,
    'budget and use what you have dinners with written method; smaller reach but very high like ratio'
  ),
  (
    'UCpSgg_ECBj25s9moCDfSTsA',
    'Jamie Oliver',
    '@jamieoliver',
    'https://www.youtube.com/@jamieoliver',
    6220000,
    1105267979,
    47929,
    504,
    null,
    'Medium',
    'intl_added',
    true,
    'quick-meal focus and huge catalog, but no written ingredients on YouTube'
  ),
  (
    'UCqNkn5PNeSqbQTAR5RP-L-Q',
    'Andy Cooks (Andy Hearnden)',
    '@andy_cooks',
    'https://www.youtube.com/@andy_cooks',
    6320000,
    3807441399,
    566064,
    6708,
    null,
    'Medium',
    'intl_added',
    true,
    'big engagement and dinner recipes, but a pro-chef lens and recipes off-platform'
  )
on conflict (youtube_channel_id) do update set
  display_name = excluded.display_name,
  handle = excluded.handle,
  channel_url = excluded.channel_url,
  subscriber_count = excluded.subscriber_count,
  total_views = excluded.total_views,
  avg_views = excluded.avg_views,
  avg_likes = excluded.avg_likes,
  rank = excluded.rank,
  fit = excluded.fit,
  source = excluded.source,
  enabled = excluded.enabled,
  notes = excluded.notes,
  updated_at = now();
