-- ~539 popular US dinner dishes for library generation queue

insert into public.library_dish_queue (dish_name, status, attempts)
values
  ('Classic Beef Tacos', 'pending', 0),
  ('Chicken Enchiladas', 'pending', 0),
  ('Cheesy Beef Burritos', 'pending', 0),
  ('Ground Beef Nachos', 'pending', 0),
  ('Slow Cooker Carnitas', 'pending', 0),
  ('Pork Carnitas Bowls', 'pending', 0),
  ('Carne Asada Tacos', 'pending', 0),
  ('Shrimp Fajitas', 'pending', 0),
  ('Vegetable Fajitas', 'pending', 0),
  ('Chicken Quesadillas', 'pending', 0),
  ('Beef Quesadillas', 'pending', 0),
  ('Chicken Tortilla Soup', 'pending', 0),
  ('Pozole Rojo', 'pending', 0),
  ('Green Chile Chicken Stew', 'pending', 0),
  ('Mexican Rice and Beans', 'pending', 0),
  ('Cilantro Lime Rice', 'pending', 0),
  ('Street Corn Salad', 'pending', 0),
  ('Elote Pasta', 'pending', 0),
  ('Chipotle Chicken Bowls', 'pending', 0),
  ('Barbacoa Beef Bowls', 'pending', 0),
  ('Spaghetti and Meatballs', 'pending', 0),
  ('Baked Ziti', 'pending', 0),
  ('Chicken Alfredo', 'pending', 0),
  ('Fettuccine Alfredo', 'pending', 0),
  ('Penne Arrabbiata', 'pending', 0),
  ('Marinara Pasta', 'pending', 0),
  ('Pesto Pasta with Chicken', 'pending', 0),
  ('Lasagna', 'pending', 0),
  ('Stuffed Shells', 'pending', 0),
  ('Chicken Parmesan', 'pending', 0),
  ('Eggplant Parmesan', 'pending', 0),
  ('Meatball Subs', 'pending', 0),
  ('Italian Sausage and Peppers', 'pending', 0),
  ('Sausage and Potato Skillet', 'pending', 0),
  ('Chicken Marsala', 'pending', 0),
  ('Tuscan White Bean Soup', 'pending', 0),
  ('Minestrone', 'pending', 0),
  ('Italian Wedding Soup', 'pending', 0),
  ('Caprese Chicken', 'pending', 0),
  ('Baked Chicken Parmesan', 'pending', 0),
  ('Beef Stroganoff', 'pending', 0),
  ('Chicken and Dumplings', 'pending', 0),
  ('Pot Roast', 'pending', 0),
  ('Swedish Meatballs', 'pending', 0),
  ('Beef and Noodles', 'pending', 0),
  ('Shepherd Pie', 'pending', 0),
  ('Cottage Pie', 'pending', 0),
  ('Meatloaf with Mashed Potatoes', 'pending', 0),
  ('Salisbury Steak', 'pending', 0),
  ('Beef Pot Pie', 'pending', 0),
  ('Chicken Pot Pie', 'pending', 0),
  ('Turkey Pot Pie', 'pending', 0),
  ('Chicken and Rice Casserole', 'pending', 0),
  ('Tuna Noodle Casserole', 'pending', 0),
  ('Hamburger Helper Style Skillet', 'pending', 0),
  ('Sloppy Joes', 'pending', 0),
  ('Beef and Broccoli', 'pending', 0),
  ('Mongolian Beef', 'pending', 0),
  ('Orange Chicken', 'pending', 0),
  ('General Tso Chicken', 'pending', 0),
  ('Fried Rice', 'pending', 0),
  ('Chicken Fried Rice', 'pending', 0),
  ('Beef Fried Rice', 'pending', 0),
  ('Vegetable Fried Rice', 'pending', 0),
  ('Lo Mein', 'pending', 0),
  ('Chicken Lo Mein', 'pending', 0),
  ('Beef Lo Mein', 'pending', 0),
  ('Chow Mein', 'pending', 0),
  ('Beef and Broccoli Stir Fry', 'pending', 0),
  ('Kung Pao Chicken', 'pending', 0),
  ('Sweet and Sour Chicken', 'pending', 0),
  ('Sesame Chicken', 'pending', 0),
  ('Honey Garlic Chicken', 'pending', 0),
  ('Teriyaki Chicken', 'pending', 0),
  ('Teriyaki Salmon', 'pending', 0),
  ('Miso Salmon', 'pending', 0),
  ('Shrimp Stir Fry', 'pending', 0),
  ('Pad Thai', 'pending', 0),
  ('Drunken Noodles', 'pending', 0),
  ('Thai Basil Chicken', 'pending', 0),
  ('Chicken Curry', 'pending', 0),
  ('Chickpea Curry', 'pending', 0),
  ('Lentil Curry', 'pending', 0),
  ('Butter Chicken', 'pending', 0),
  ('Chicken Tikka Masala', 'pending', 0),
  ('Palak Paneer', 'pending', 0),
  ('Chana Masala', 'pending', 0),
  ('Dal Tadka', 'pending', 0),
  ('Biryani', 'pending', 0),
  ('Chicken Biryani', 'pending', 0),
  ('Beef Kofta', 'pending', 0),
  ('Lamb Stew', 'pending', 0),
  ('Greek Chicken Souvlaki', 'pending', 0),
  ('Gyro Bowls', 'pending', 0),
  ('Moussaka', 'pending', 0),
  ('Shakshuka', 'pending', 0),
  ('Falafel Bowls', 'pending', 0),
  ('Hummus Bowls', 'pending', 0),
  ('Mediterranean Chicken', 'pending', 0),
  ('Lemon Herb Chicken', 'pending', 0),
  ('Jambalaya', 'pending', 0),
  ('Gumbo', 'pending', 0),
  ('Red Beans and Rice', 'pending', 0),
  ('Shrimp and Grits', 'pending', 0),
  ('Cajun Chicken Pasta', 'pending', 0),
  ('Blackened Fish', 'pending', 0),
  ('Fish and Chips', 'pending', 0),
  ('Baked Cod', 'pending', 0),
  ('Lemon Garlic Salmon', 'pending', 0),
  ('Honey Mustard Salmon', 'pending', 0),
  ('Tilapia with Capers', 'pending', 0),
  ('Shrimp Scampi', 'pending', 0),
  ('Linguine with Clams', 'pending', 0),
  ('Cioppino', 'pending', 0),
  ('Seafood Paella', 'pending', 0),
  ('Chicken Paella', 'pending', 0),
  ('Beef Bourguignon', 'pending', 0),
  ('Coq au Vin', 'pending', 0),
  ('French Onion Soup', 'pending', 0),
  ('Ratatouille', 'pending', 0),
  ('Chicken Noodle Soup', 'pending', 0),
  ('Tomato Soup with Grilled Cheese', 'pending', 0),
  ('Broccoli Cheddar Soup', 'pending', 0),
  ('Potato Soup', 'pending', 0),
  ('Split Pea Soup', 'pending', 0),
  ('Lentil Soup', 'pending', 0),
  ('White Chicken Chili', 'pending', 0),
  ('Turkey Chili', 'pending', 0),
  ('Beef Chili', 'pending', 0),
  ('Three Bean Chili', 'pending', 0),
  ('Chili Mac', 'pending', 0),
  ('Taco Soup', 'pending', 0),
  ('Ham and Bean Soup', 'pending', 0),
  ('Sausage Kale Soup', 'pending', 0),
  ('Butternut Squash Soup', 'pending', 0),
  ('Roasted Vegetable Soup', 'pending', 0),
  ('Chicken Tortellini Soup', 'pending', 0),
  ('Pho Inspired Noodle Soup', 'pending', 0),
  ('Ramen Style Noodle Bowl', 'pending', 0),
  ('Udon Noodle Soup', 'pending', 0),
  ('BBQ Pulled Pork', 'pending', 0),
  ('BBQ Chicken Sandwiches', 'pending', 0),
  ('Smoked Brisket Tacos', 'pending', 0),
  ('Carolina Pulled Chicken', 'pending', 0),
  ('Kansas City Ribs', 'pending', 0),
  ('Baby Back Ribs', 'pending', 0),
  ('Brisket Chili', 'pending', 0),
  ('Burnt Ends Mac and Cheese', 'pending', 0),
  ('BBQ Meatball Sliders', 'pending', 0),
  ('Grilled Chicken Thighs', 'pending', 0),
  ('Grilled Steak', 'pending', 0),
  ('Hamburgers', 'pending', 0),
  ('Cheeseburgers', 'pending', 0),
  ('Smash Burgers', 'pending', 0),
  ('Turkey Burgers', 'pending', 0),
  ('Veggie Burgers', 'pending', 0),
  ('Hot Dogs', 'pending', 0),
  ('Chili Dogs', 'pending', 0),
  ('Philly Cheesesteak', 'pending', 0),
  ('French Dip Sandwiches', 'pending', 0),
  ('Chicken Wings', 'pending', 0),
  ('Buffalo Chicken Dip', 'pending', 0),
  ('Nashville Hot Chicken', 'pending', 0),
  ('Fried Chicken', 'pending', 0),
  ('Oven Fried Chicken', 'pending', 0),
  ('Chicken Tenders', 'pending', 0),
  ('Popcorn Chicken', 'pending', 0),
  ('Chicken and Waffles', 'pending', 0),
  ('Biscuits and Gravy', 'pending', 0),
  ('Breakfast Burritos', 'pending', 0),
  ('Egg and Cheese Sandwiches', 'pending', 0),
  ('Pancakes and Sausage', 'pending', 0),
  ('French Toast Bake', 'pending', 0),
  ('Overnight Oats', 'pending', 0),
  ('Egg Muffins', 'pending', 0),
  ('Shakshuka for Two', 'pending', 0),
  ('Avocado Toast with Eggs', 'pending', 0),
  ('Huevos Rancheros', 'pending', 0),
  ('Breakfast Quesadillas', 'pending', 0),
  ('Sausage Gravy Biscuits', 'pending', 0),
  ('Sheet Pan Sausage and Veggies', 'pending', 0),
  ('Sheet Pan Chicken Fajitas', 'pending', 0),
  ('Sheet Pan Gnocchi', 'pending', 0),
  ('Sheet Pan Salmon', 'pending', 0),
  ('Sheet Pan Meatballs', 'pending', 0),
  ('One Pan Chicken and Rice', 'pending', 0),
  ('One Pan Taco Rice', 'pending', 0),
  ('Skillet Lasagna', 'pending', 0),
  ('Skillet Mac and Cheese', 'pending', 0),
  ('Skillet Chicken Pot Pie', 'pending', 0),
  ('Dutch Oven Pot Roast', 'pending', 0),
  ('Dutch Oven Chili', 'pending', 0),
  ('Crockpot Pot Roast', 'pending', 0),
  ('Crockpot Chicken Tacos', 'pending', 0),
  ('Crockpot Beef Stew', 'pending', 0),
  ('Crockpot White Chicken Chili', 'pending', 0),
  ('Crockpot Pulled Pork', 'pending', 0),
  ('Crockpot Honey Garlic Chicken', 'pending', 0),
  ('Crockpot Swedish Meatballs', 'pending', 0),
  ('Instant Pot Beef Stew', 'pending', 0),
  ('Stuffed Peppers', 'pending', 0),
  ('Stuffed Cabbage Rolls', 'pending', 0),
  ('Cabbage and Sausage Skillet', 'pending', 0),
  ('Kielbasa and Sauerkraut', 'pending', 0),
  ('Pierogi Skillet', 'pending', 0),
  ('Chicken Paprikash', 'pending', 0),
  ('Goulash', 'pending', 0),
  ('Beef Goulash', 'pending', 0),
  ('Hungarian Chicken', 'pending', 0),
  ('Polish Sausage and Potatoes', 'pending', 0),
  ('German Bratwurst and Onions', 'pending', 0),
  ('Schnitzel with Potatoes', 'pending', 0),
  ('Chicken Schnitzel', 'pending', 0),
  ('Beef and Barley Stew', 'pending', 0),
  ('Irish Stew', 'pending', 0),
  ('Corned Beef and Cabbage', 'pending', 0),
  ('Fish Pie', 'pending', 0),
  ('Bangers and Mash', 'pending', 0),
  ('Toad in the Hole', 'pending', 0),
  ('Shepherds Pie with Lamb', 'pending', 0),
  ('Vegetable Stir Fry', 'pending', 0),
  ('Roasted Vegetable Pasta', 'pending', 0),
  ('Caprese Pasta', 'pending', 0),
  ('Spinach and Ricotta Pasta', 'pending', 0),
  ('Mushroom Risotto', 'pending', 0),
  ('Chicken Risotto', 'pending', 0),
  ('Shrimp Risotto', 'pending', 0),
  ('Arroz con Pollo', 'pending', 0),
  ('Chicken and Black Bean Bowls', 'pending', 0),
  ('Quinoa Bowls', 'pending', 0),
  ('Buddha Bowls', 'pending', 0),
  ('Grain Bowls with Roasted Veg', 'pending', 0),
  ('Sweet Potato Chili', 'pending', 0),
  ('Black Bean Soup', 'pending', 0),
  ('Vegetable Curry', 'pending', 0),
  ('Cauliflower Curry', 'pending', 0),
  ('Roasted Cauliflower Steaks', 'pending', 0),
  ('Stuffed Sweet Potatoes', 'pending', 0),
  ('Black Bean Tacos', 'pending', 0),
  ('Lentil Tacos', 'pending', 0),
  ('Margherita Pizza', 'pending', 0),
  ('Pepperoni Pizza', 'pending', 0),
  ('Sausage Pizza', 'pending', 0),
  ('BBQ Chicken Pizza', 'pending', 0),
  ('Flatbread Pizza', 'pending', 0),
  ('Calzones', 'pending', 0),
  ('Stromboli', 'pending', 0),
  ('Garlic Knots with Marinara', 'pending', 0),
  ('Chicken Caesar Salad', 'pending', 0),
  ('Cobb Salad', 'pending', 0),
  ('Chef Salad', 'pending', 0),
  ('Taco Salad', 'pending', 0),
  ('Southwest Salad', 'pending', 0),
  ('Greek Salad with Chicken', 'pending', 0),
  ('Asian Chicken Salad', 'pending', 0),
  ('Wedge Salad with Blue Cheese', 'pending', 0),
  ('BLT Sandwiches', 'pending', 0),
  ('Club Sandwiches', 'pending', 0),
  ('Tuna Melts', 'pending', 0),
  ('Patty Melts', 'pending', 0),
  ('Chicken Piccata', 'pending', 0),
  ('Lemon Pepper Chicken', 'pending', 0),
  ('Garlic Butter Shrimp', 'pending', 0),
  ('Cajun Shrimp Pasta', 'pending', 0),
  ('Creamy Tuscan Chicken', 'pending', 0),
  ('Creamy Mushroom Chicken', 'pending', 0),
  ('Marry Me Chicken', 'pending', 0),
  ('Sun Dried Tomato Chicken', 'pending', 0),
  ('Spinach Artichoke Chicken', 'pending', 0),
  ('Buffalo Chicken Wraps', 'pending', 0),
  ('Chicken Caesar Wraps', 'pending', 0),
  ('Turkey Club Wraps', 'pending', 0),
  ('Ham and Cheese Paninis', 'pending', 0),
  ('Grilled Cheese', 'pending', 0),
  ('Tomato Basil Soup', 'pending', 0),
  ('Roasted Tomato Pasta', 'pending', 0),
  ('Baked Mac and Cheese', 'pending', 0),
  ('Broccoli Chicken Casserole', 'pending', 0),
  ('Green Bean Casserole', 'pending', 0),
  ('Corn Casserole', 'pending', 0),
  ('Beef Tacos Dorados', 'pending', 0),
  ('Chicken Tinga Tacos', 'pending', 0),
  ('Fish Tacos', 'pending', 0),
  ('Shrimp Tacos', 'pending', 0),
  ('Carnitas Tostadas', 'pending', 0),
  ('Chilaquiles', 'pending', 0),
  ('Breakfast Tostadas', 'pending', 0),
  ('Pork Adobo', 'pending', 0),
  ('Chicken Adobo', 'pending', 0),
  ('Filipino Pancit', 'pending', 0),
  ('Beef Bulgogi', 'pending', 0),
  ('Korean Beef Bowls', 'pending', 0),
  ('Kimchi Fried Rice', 'pending', 0),
  ('Bibimbap Bowls', 'pending', 0),
  ('Japanese Curry', 'pending', 0),
  ('Chicken Katsu', 'pending', 0),
  ('Tonkatsu', 'pending', 0),
  ('Yakitori Chicken', 'pending', 0),
  ('Miso Soup with Tofu', 'pending', 0),
  ('Teriyaki Meatballs', 'pending', 0),
  ('Moroccan Chicken Tagine', 'pending', 0),
  ('Harissa Roasted Chicken', 'pending', 0),
  ('Lamb Tagine', 'pending', 0),
  ('Couscous Bowls', 'pending', 0),
  ('Fattoush Salad', 'pending', 0),
  ('Tabbouleh Bowls', 'pending', 0),
  ('Stuffed Grape Leaves', 'pending', 0),
  ('Kebab Plates', 'pending', 0),
  ('Chicken Shawarma', 'pending', 0),
  ('Beef Shawarma', 'pending', 0),
  ('Falafel Pitas', 'pending', 0),
  ('Gyro Pitas', 'pending', 0),
  ('Spanakopita Pie', 'pending', 0),
  ('Greek Lemon Potatoes', 'pending', 0),
  ('Roasted Greek Chicken', 'pending', 0),
  ('Mediterranean Orzo', 'pending', 0),
  ('Orzo Salad', 'pending', 0),
  ('Pasta Primavera', 'pending', 0),
  ('Spring Vegetable Pasta', 'pending', 0),
  ('Summer Squash Pasta', 'pending', 0),
  ('Chicken and Biscuits', 'pending', 0),
  ('Turkey and Gravy', 'pending', 0),
  ('Roast Turkey Breast', 'pending', 0),
  ('Glazed Ham', 'pending', 0),
  ('Honey Baked Ham Slices', 'pending', 0),
  ('Pork Chops with Apples', 'pending', 0),
  ('Pork Tenderloin', 'pending', 0),
  ('Pork Loin Roast', 'pending', 0),
  ('Boneless Pork Ribs', 'pending', 0),
  ('Country Style Ribs', 'pending', 0),
  ('Beef Brisket Sandwiches', 'pending', 0),
  ('Potato Wedges', 'pending', 0),
  ('Roasted Root Vegetables', 'pending', 0),
  ('Garlic Mashed Potatoes', 'pending', 0),
  ('Scalloped Potatoes', 'pending', 0),
  ('Au Gratin Potatoes', 'pending', 0),
  ('Cornbread', 'pending', 0),
  ('Cornbread Casserole', 'pending', 0),
  ('Mac and Cheese Bake', 'pending', 0),
  ('Baked Beans', 'pending', 0),
  ('Chicken Satay', 'pending', 0),
  ('Peanut Noodles', 'pending', 0),
  ('Cold Sesame Noodles', 'pending', 0),
  ('Dan Dan Noodles', 'pending', 0),
  ('Szechuan Green Beans', 'pending', 0),
  ('Egg Drop Soup', 'pending', 0),
  ('Hot and Sour Soup', 'pending', 0),
  ('Wonton Soup', 'pending', 0),
  ('Dumpling Soup', 'pending', 0),
  ('Potstickers with Rice', 'pending', 0),
  ('Egg Foo Young', 'pending', 0),
  ('Cashew Chicken', 'pending', 0),
  ('Walnut Shrimp', 'pending', 0),
  ('Lemon Chicken', 'pending', 0),
  ('Garlic Noodles', 'pending', 0),
  ('Shrimp Po Boys', 'pending', 0),
  ('Crab Cakes', 'pending', 0),
  ('Lobster Mac and Cheese', 'pending', 0),
  ('Clam Chowder', 'pending', 0),
  ('New England Chowder', 'pending', 0),
  ('Vegetable Lasagna', 'pending', 0),
  ('Eggplant Rollatini', 'pending', 0),
  ('Zucchini Boats', 'pending', 0),
  ('Stuffed Zucchini', 'pending', 0),
  ('Stuffed Mushrooms', 'pending', 0),
  ('Portobello Burgers', 'pending', 0),
  ('Cauliflower Alfredo', 'pending', 0),
  ('Cauliflower Mac and Cheese', 'pending', 0),
  ('Broccoli Chicken Stir Fry', 'pending', 0),
  ('Sesame Tofu', 'pending', 0),
  ('Tofu Curry', 'pending', 0),
  ('Tofu Fried Rice', 'pending', 0),
  ('Blackened Chicken Pasta', 'pending', 0),
  ('Cajun Shrimp Boil', 'pending', 0),
  ('Low Country Boil', 'pending', 0),
  ('Shrimp Boil Foil Packs', 'pending', 0),
  ('Lobster Rolls', 'pending', 0),
  ('Crab Salad Sandwiches', 'pending', 0),
  ('Tuna Salad Sandwiches', 'pending', 0),
  ('Chicken Salad Sandwiches', 'pending', 0),
  ('Rotisserie Chicken Tacos', 'pending', 0),
  ('Rotisserie Chicken Soup', 'pending', 0),
  ('Rotisserie Chicken Alfredo', 'pending', 0),
  ('Leftover Turkey Soup', 'pending', 0),
  ('Leftover Ham Mac and Cheese', 'pending', 0),
  ('Turkey Tetrazzini', 'pending', 0),
  ('Chicken Tetrazzini', 'pending', 0),
  ('Ham and Potato Casserole', 'pending', 0),
  ('Sausage Breakfast Casserole', 'pending', 0),
  ('Hash Brown Casserole', 'pending', 0),
  ('Tater Tot Casserole', 'pending', 0),
  ('Pizza Casserole', 'pending', 0),
  ('Taco Casserole', 'pending', 0),
  ('Enchilada Casserole', 'pending', 0),
  ('Burrito Casserole', 'pending', 0),
  ('Shepherd Salad', 'pending', 0),
  ('Chef Inspired Meatballs', 'pending', 0),
  ('Swedish Meatball Pasta', 'pending', 0),
  ('Meatball Bake', 'pending', 0),
  ('Sausage Pasta Bake', 'pending', 0),
  ('Air Fryer Chicken Thighs', 'pending', 0),
  ('Air Fryer Salmon', 'pending', 0),
  ('Air Fryer Pork Chops', 'pending', 0),
  ('Air Fryer Chicken Wings', 'pending', 0),
  ('Air Fryer Fish', 'pending', 0),
  ('Air Fryer Taquitos', 'pending', 0),
  ('Air Fryer Quesadillas', 'pending', 0),
  ('Air Fryer Meatballs', 'pending', 0),
  ('Grilled Pork Tenderloin', 'pending', 0),
  ('Grilled Veggie Skewers', 'pending', 0),
  ('Grilled Chicken Skewers', 'pending', 0),
  ('Grilled Shrimp Skewers', 'pending', 0),
  ('Steak Fajitas', 'pending', 0),
  ('Steak and Potatoes', 'pending', 0),
  ('Surf and Turf Skillet', 'pending', 0),
  ('Garlic Steak Bites', 'pending', 0),
  ('Pepper Steak', 'pending', 0),
  ('Steak Stir Fry', 'pending', 0),
  ('Beef and Peppers', 'pending', 0),
  ('Pepperoncini Beef', 'pending', 0),
  ('Chicken and Orzo', 'pending', 0),
  ('Lemon Orzo with Chicken', 'pending', 0),
  ('Spinach Tortellini Soup', 'pending', 0),
  ('Baked Ravioli', 'pending', 0),
  ('Cheesy Ravioli Bake', 'pending', 0),
  ('Manicotti', 'pending', 0),
  ('Cannelloni', 'pending', 0),
  ('Bolognese Pasta', 'pending', 0),
  ('Pasta e Fagioli', 'pending', 0),
  ('Pasta Carbonara', 'pending', 0),
  ('Amatriciana', 'pending', 0),
  ('Cacio e Pepe', 'pending', 0),
  ('Gnocchi with Sage Butter', 'pending', 0),
  ('Brown Butter Gnocchi', 'pending', 0),
  ('Pumpkin Pasta', 'pending', 0),
  ('Butternut Squash Mac and Cheese', 'pending', 0),
  ('Apple Chicken Sausage Skillet', 'pending', 0),
  ('Maple Dijon Chicken', 'pending', 0),
  ('Cider Glazed Pork', 'pending', 0),
  ('Apple Pork Chops', 'pending', 0),
  ('Harvest Chicken Sheet Pan', 'pending', 0),
  ('Fall Vegetable Stew', 'pending', 0),
  ('Winter Vegetable Soup', 'pending', 0),
  ('Spring Pea Pasta', 'pending', 0),
  ('Asparagus Chicken', 'pending', 0),
  ('Lemon Asparagus Pasta', 'pending', 0),
  ('Zucchini Pasta', 'pending', 0),
  ('Tomato Cucumber Salad Bowls', 'pending', 0),
  ('Caprese Chicken Bake', 'pending', 0),
  ('Bruschetta Chicken', 'pending', 0),
  ('Panzanella Salad', 'pending', 0),
  ('Antipasto Pasta', 'pending', 0),
  ('Italian Sub Bake', 'pending', 0),
  ('Meatball Sub Bake', 'pending', 0),
  ('Pizza Bagels', 'pending', 0),
  ('Bagel Breakfast Bake', 'pending', 0),
  ('Overnight French Toast', 'pending', 0),
  ('Banana Pancakes', 'pending', 0),
  ('Blueberry Muffin Bake', 'pending', 0),
  ('Oatmeal Bake', 'pending', 0),
  ('Chicken Souvlaki Bowls', 'pending', 0),
  ('Greek Meatball Bowls', 'pending', 0),
  ('Mediterranean Lentil Soup', 'pending', 0),
  ('Red Lentil Soup', 'pending', 0),
  ('Moroccan Lentil Stew', 'pending', 0),
  ('Chickpea Stew', 'pending', 0),
  ('White Bean Chicken Chili', 'pending', 0),
  ('Turkey Meatball Soup', 'pending', 0),
  ('Italian Meatball Soup', 'pending', 0),
  ('Wedding Soup with Meatballs', 'pending', 0),
  ('Sausage Tortellini Soup', 'pending', 0),
  ('Creamy Tomato Tortellini', 'pending', 0),
  ('Spinach Tortellini', 'pending', 0),
  ('Pesto Tortellini', 'pending', 0),
  ('Sun Dried Tomato Tortellini', 'pending', 0),
  ('Chicken Pesto Pasta', 'pending', 0),
  ('Basil Chicken', 'pending', 0),
  ('Tomato Basil Chicken', 'pending', 0),
  ('Bruschetta Pasta', 'pending', 0),
  ('Roasted Red Pepper Pasta', 'pending', 0),
  ('Creamy Chicken and Wild Rice', 'pending', 0),
  ('Wild Rice Soup', 'pending', 0),
  ('Mushroom Wild Rice Skillet', 'pending', 0),
  ('Chicken and Mushroom Skillet', 'pending', 0),
  ('Steak and Mushroom Skillet', 'pending', 0),
  ('Pork and Apple Skillet', 'pending', 0),
  ('Sausage and Peppers Pasta', 'pending', 0),
  ('Pepperoni Pasta Bake', 'pending', 0),
  ('Pizza Pasta', 'pending', 0),
  ('Taco Pasta', 'pending', 0),
  ('Buffalo Chicken Pasta', 'pending', 0),
  ('Ranch Chicken Pasta', 'pending', 0),
  ('Hawaiian Pizza', 'pending', 0),
  ('Breakfast Pizza', 'pending', 0),
  ('Pita Pizzas', 'pending', 0),
  ('Naan Pizzas', 'pending', 0),
  ('Flatbread Caprese', 'pending', 0),
  ('Prosciutto Melon Salad Dinner', 'pending', 0),
  ('Antipasto Chicken', 'pending', 0),
  ('Crispy Baked Tofu Bowls', 'pending', 0),
  ('Tempeh Stir Fry', 'pending', 0),
  ('Veggie Chili', 'pending', 0),
  ('Mushroom Stroganoff', 'pending', 0),
  ('Lentil Shepherd Pie', 'pending', 0),
  ('Bean and Cheese Burritos', 'pending', 0),
  ('Refried Bean Tostadas', 'pending', 0),
  ('Cheese Enchiladas', 'pending', 0),
  ('Spinach Enchiladas', 'pending', 0),
  ('Chicken Enchilada Skillet', 'pending', 0),
  ('Beef Enchilada Casserole', 'pending', 0),
  ('Tamale Pie', 'pending', 0),
  ('Frito Pie', 'pending', 0),
  ('Walking Tacos', 'pending', 0),
  ('Taco Stuffed Shells', 'pending', 0),
  ('Queso Chicken Skillet', 'pending', 0),
  ('Nacho Chicken Skillet', 'pending', 0),
  ('Loaded Baked Potatoes', 'pending', 0),
  ('Twice Baked Potatoes', 'pending', 0),
  ('Baked Potato Bar', 'pending', 0),
  ('Garlic Herb Pork Roast', 'pending', 0),
  ('Herb Roasted Chicken', 'pending', 0),
  ('Roast Chicken Dinner', 'pending', 0),
  ('Sunday Pot Roast', 'pending', 0),
  ('Yorkshire Pudding Skillet', 'pending', 0),
  ('Beef and Mushroom Pie', 'pending', 0),
  ('Chicken and Leek Pie', 'pending', 0),
  ('Turkey Pot Pie Skillet', 'pending', 0),
  ('Ham Scalloped Potatoes', 'pending', 0),
  ('Sausage and Gravy over Rice', 'pending', 0),
  ('Red Beans Sausage Rice', 'pending', 0),
  ('Hoppin John', 'pending', 0),
  ('Jollof Inspired Rice', 'pending', 0),
  ('Jambalaya Pasta', 'pending', 0),
  ('Dirty Rice', 'pending', 0),
  ('Spanish Rice Chicken', 'pending', 0),
  ('Arroz con Gandules Style', 'pending', 0),
  ('Puerto Rican Chicken Stew', 'pending', 0),
  ('Ropa Vieja', 'pending', 0),
  ('Picadillo', 'pending', 0)
on conflict (dish_name) do nothing;
